% Auto generated function to compile/launch ModelSim simulator
% 
% Generated by MATLAB 9.13 and HDL Coder 4.0

function launch_modelo_base_fixpt_cosim
% Make sure there is no HDL simulator using the communication channel
pid = pingHdlSim(1);
if pid > 0
   error('hdlverifier:mlhdlc:HDLServerExist','Another instance of HDL simulator exists. Close all HDL simulator instances and try again');
end
currentdir = cd('C:\Users\juand\Documents\MATLAB\Resultados\modelo_base\modelo_base_hdl\modelo_base\hdlsrc');
onCleanupObj = onCleanup(@() cd(currentdir));
% Pre-sim TCL commands
tclCmds = { ...
    'vlib work',...% Compile the generated code
    'vlog modelo_base_fixpt.v',...
    'vsimmatlabsysobj -voptargs=+acc work.modelo_base_fixpt',...% Initiate cosimulation
    'set UserTimeUnit ns',...% Set simulation time unit
    'puts ""',...
    'puts "Ready for cosimulation..."',...
};
% Launch HDL simulator
vsim('tclstart',tclCmds,'runmode','Batch');

% Wait for HDL simulator to ready
disp('### Waiting for ModelSim to start ');
pingHdlSim(180);

