% Function localRecompile_modelo_base_wrapper_fixpt_cosim recreates a MEX-function modelo_base_wrapper_fixpt_cosim_mex from MATLAB function modelo_base_wrapper_fixpt_cosim
% Generated by MATLAB 9.13 and HDL Coder 4.0
function localRecompile_modelo_base_wrapper_fixpt_cosim

load('C:\Users\juand\Documents\MATLAB\Resultados\modelo_base\modelo_base_hdl\modelo_base\cosim\localCodegenArgs_modelo_base_wrapper_fixpt_cosim');

fxptPath = 'C:\Users\juand\Documents\MATLAB\Resultados\modelo_base\modelo_base_hdl\modelo_base\fixpt';
addpath(fxptPath);
cleanupObj = onCleanup(@() rmpath(fxptPath));
codegen -args exInputs -o 'C:\Users\juand\Documents\MATLAB\Resultados\modelo_base\modelo_base_hdl\modelo_base\cosim\modelo_base_wrapper_fixpt_cosim_mex' modelo_base_wrapper_fixpt_cosim;

