% Auto generated function to simulate the generated HDL code using cosimulation
% 
% Generated by MATLAB 9.13 and HDL Coder 4.0

function ref_out = modelo_base_fixpt_cosim(in)

coder.extrinsic('modelo_base_fixpt_sysobj_cosim');
coder.extrinsic('hdlverifier.assert');
coder.extrinsic('hdlverifier.Delay');
coder.extrinsic('step');

% Declare persistent variables
persistent initialized;

% Initialize persistent variables
if isempty(initialized)
   initialized = true;
end

% Call the original MATLAB function to get reference signal
ref_out = modelo_base_fixpt(in);

% Convert input signals
in_1 = in(1);

in_2 = in(2);

in_3 = in(3);

in_4 = in(4);

in_5 = in(5);

in_6 = in(6);

in_7 = in(7);

in_8 = in(8);

in_9 = in(9);

in_10 = in(10);

in_11 = in(11);

in_12 = in(12);

in_13 = in(13);

in_14 = in(14);

in_15 = in(15);

in_16 = in(16);

in_17 = in(17);

in_18 = in(18);

in_19 = in(19);

in_20 = in(20);

in_21 = in(21);

in_22 = in(22);

in_23 = in(23);

in_24 = in(24);

in_25 = in(25);

in_26 = in(26);

in_27 = in(27);

in_28 = in(28);

in_29 = in(29);

in_30 = in(30);



% Run cosimulation
out = modelo_base_fixpt_sysobj_cosim(in_1,in_2,in_3,in_4,in_5,in_6,in_7,in_8,in_9,in_10,in_11,in_12,in_13,in_14,in_15,in_16,in_17,in_18,in_19,in_20,in_21,in_22,in_23,in_24,in_25,in_26,in_27,in_28,in_29,in_30);

% Verify the cosimulation output
hdlverifier.assert(out,ref_out,'out');

