// -------------------------------------------------------------
// 
// File Name: C:\Users\juand\Documents\MATLAB\Resultados\modelo_base\modelo_base_hdl\modelo_base\hdlsrc\modelo_base_fixpt.v
// Created: 2022-12-10 19:53:33
// 
// Generated by MATLAB 9.13, MATLAB Coder 5.5 and HDL Coder 4.0
// 
// 
// 
// -- -------------------------------------------------------------
// -- Rate and Clocking Details
// -- -------------------------------------------------------------
// Design base rate: 1
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: modelo_base_fixpt
// Source Path: modelo_base_fixpt
// Hierarchy Level: 0
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module modelo_base_fixpt
          (in_0,
           in_1,
           in_2,
           in_3,
           in_4,
           in_5,
           in_6,
           in_7,
           in_8,
           in_9,
           in_10,
           in_11,
           in_12,
           in_13,
           in_14,
           in_15,
           in_16,
           in_17,
           in_18,
           in_19,
           in_20,
           in_21,
           in_22,
           in_23,
           in_24,
           in_25,
           in_26,
           in_27,
           in_28,
           in_29,
           out);


  input   [15:0] in_0;  // ufix16_En15
  input   [15:0] in_1;  // ufix16_En15
  input   [15:0] in_2;  // ufix16_En15
  input   [15:0] in_3;  // ufix16_En15
  input   [15:0] in_4;  // ufix16_En15
  input   [15:0] in_5;  // ufix16_En15
  input   [15:0] in_6;  // ufix16_En15
  input   [15:0] in_7;  // ufix16_En15
  input   [15:0] in_8;  // ufix16_En15
  input   [15:0] in_9;  // ufix16_En15
  input   [15:0] in_10;  // ufix16_En15
  input   [15:0] in_11;  // ufix16_En15
  input   [15:0] in_12;  // ufix16_En15
  input   [15:0] in_13;  // ufix16_En15
  input   [15:0] in_14;  // ufix16_En15
  input   [15:0] in_15;  // ufix16_En15
  input   [15:0] in_16;  // ufix16_En15
  input   [15:0] in_17;  // ufix16_En15
  input   [15:0] in_18;  // ufix16_En15
  input   [15:0] in_19;  // ufix16_En15
  input   [15:0] in_20;  // ufix16_En15
  input   [15:0] in_21;  // ufix16_En15
  input   [15:0] in_22;  // ufix16_En15
  input   [15:0] in_23;  // ufix16_En15
  input   [15:0] in_24;  // ufix16_En15
  input   [15:0] in_25;  // ufix16_En15
  input   [15:0] in_26;  // ufix16_En15
  input   [15:0] in_27;  // ufix16_En15
  input   [15:0] in_28;  // ufix16_En15
  input   [15:0] in_29;  // ufix16_En15
  output  out;  // ufix1


  wire [15:0] in [0:29];  // ufix16_En15 [30]
  reg  out_1;  // ufix1
  reg signed [15:0] modelo_base_fixpt_acum;  // sfix16_En12
  reg signed [15:0] modelo_base_fixpt_acum_0;  // sfix16_En12
  reg signed [15:0] modelo_base_fixpt_tmp;  // sfix16_En12
  reg signed [31:0] modelo_base_fixpt_a1;  // sfix32_En28
  reg signed [49:0] modelo_base_fixpt_tmp_0;  // sfix50_En28
  reg signed [17:0] modelo_base_fixpt_b1;  // sfix18_En12
  reg [15:0] modelo_base_fixpt_tmp_1;  // ufix16_En14
  reg signed [15:0] modelo_base_fixpt_acum_1;  // sfix16_En13
  reg signed [15:0] modelo_base_fixpt_acum_2;  // sfix16_En13
  reg signed [31:0] modelo_base_fixpt_i;  // int32
  reg signed [31:0] modelo_base_fixpt_i_0;  // int32
  reg signed [15:0] modelo_base_fixpt_w [0:15];  // sfix16_En14 [16]
  reg signed [15:0] modelo_base_fixpt_b1_0 [0:15];  // sfix16_En15 [16]
  reg signed [15:0] modelo_base_fixpt_w1 [0:479];  // sfix16_En15 [480]
  reg signed [43:0] modelo_base_fixpt_div_temp;  // sfix44_En28
  reg signed [20:0] modelo_base_fixpt_t_0;  // sfix21_En16
  reg signed [15:0] modelo_base_fixpt_add_cast;  // sfix16_En12
  reg signed [16:0] modelo_base_fixpt_cast;  // sfix17_En12
  reg signed [16:0] modelo_base_fixpt_cast_0;  // sfix17_En12
  reg signed [18:0] modelo_base_fixpt_add_cast_0 [0:15];  // sfix19_En15 [16]
  reg signed [18:0] modelo_base_fixpt_add_cast_1 [0:15];  // sfix19_En15 [16]
  reg signed [18:0] modelo_base_fixpt_add_temp [0:15];  // sfix19_En15 [16]
  reg signed [33:0] modelo_base_fixpt_add_cast_2 [0:29];  // sfix34_En30 [30]
  reg signed [16:0] modelo_base_fixpt_cast_1 [0:29];  // sfix17_En15 [30]
  reg signed [32:0] modelo_base_fixpt_mul_temp [0:29];  // sfix33_En30 [30]
  reg signed [31:0] modelo_base_fixpt_add_cast_3 [0:29];  // sfix32_En30 [30]
  reg signed [33:0] modelo_base_fixpt_add_cast_4 [0:29];  // sfix34_En30 [30]
  reg signed [33:0] modelo_base_fixpt_add_temp_0 [0:29];  // sfix34_En30 [30]
  reg signed [32:0] modelo_base_fixpt_cast_2;  // sfix33_En28
  reg signed [32:0] modelo_base_fixpt_add_cast_5 [0:15];  // sfix33_En28 [16]
  reg signed [16:0] modelo_base_fixpt_cast_3 [0:15];  // sfix17_En14 [16]
  reg signed [32:0] modelo_base_fixpt_mul_temp_0 [0:15];  // sfix33_En28 [16]
  reg signed [31:0] modelo_base_fixpt_add_cast_6 [0:15];  // sfix32_En28 [16]
  reg signed [32:0] modelo_base_fixpt_add_cast_7 [0:15];  // sfix33_En28 [16]
  reg signed [32:0] modelo_base_fixpt_add_temp_1 [0:15];  // sfix33_En28 [16]
  reg signed [17:0] modelo_base_fixpt_add_cast_8;  // sfix18_En12
  reg signed [43:0] modelo_base_fixpt_slice_cast;  // sfix44_En40
  reg signed [43:0] modelo_base_fixpt_slice_cast_0;  // sfix44_En28
  reg signed [43:0] modelo_base_fixpt_cast_4;  // sfix44_En40
  reg signed [51:0] modelo_base_fixpt_add_cast_9;  // sfix52_En28
  reg signed [51:0] modelo_base_fixpt_add_temp_2;  // sfix52_En28
  reg [15:0] modelo_base_fixpt_cast_5;  // ufix16_En16


  assign in[0] = in_0;
  assign in[1] = in_1;
  assign in[2] = in_2;
  assign in[3] = in_3;
  assign in[4] = in_4;
  assign in[5] = in_5;
  assign in[6] = in_6;
  assign in[7] = in_7;
  assign in[8] = in_8;
  assign in[9] = in_9;
  assign in[10] = in_10;
  assign in[11] = in_11;
  assign in[12] = in_12;
  assign in[13] = in_13;
  assign in[14] = in_14;
  assign in[15] = in_15;
  assign in[16] = in_16;
  assign in[17] = in_17;
  assign in[18] = in_18;
  assign in[19] = in_19;
  assign in[20] = in_20;
  assign in[21] = in_21;
  assign in[22] = in_22;
  assign in[23] = in_23;
  assign in[24] = in_24;
  assign in[25] = in_25;
  assign in[26] = in_26;
  assign in[27] = in_27;
  assign in[28] = in_28;
  assign in[29] = in_29;

  always @* begin
    modelo_base_fixpt_w[0] = 16'sb1101111100101111;
    modelo_base_fixpt_w[1] = 16'sb0010111000010000;
    modelo_base_fixpt_w[2] = 16'sb1111000010100111;
    modelo_base_fixpt_w[3] = 16'sb0011110101101011;
    modelo_base_fixpt_w[4] = 16'sb1100000000001101;
    modelo_base_fixpt_w[5] = 16'sb1011010001110111;
    modelo_base_fixpt_w[6] = 16'sb1100000011000011;
    modelo_base_fixpt_w[7] = 16'sb1101010001001110;
    modelo_base_fixpt_w[8] = 16'sb1010111011111100;
    modelo_base_fixpt_w[9] = 16'sb0011001110100010;
    modelo_base_fixpt_w[10] = 16'sb0010001001101110;
    modelo_base_fixpt_w[11] = 16'sb0010010000011010;
    modelo_base_fixpt_w[12] = 16'sb0100000110110001;
    modelo_base_fixpt_w[13] = 16'sb1110111100110100;
    modelo_base_fixpt_w[14] = 16'sb1101010111110110;
    modelo_base_fixpt_w[15] = 16'sb0000101000101111;
    modelo_base_fixpt_b1_0[0] = 16'sb0011111111100101;
    modelo_base_fixpt_b1_0[1] = 16'sb1110010010101011;
    modelo_base_fixpt_b1_0[2] = 16'sb0010010101100000;
    modelo_base_fixpt_b1_0[3] = 16'sb1100110101011101;
    modelo_base_fixpt_b1_0[4] = 16'sb0010111011000011;
    modelo_base_fixpt_b1_0[5] = 16'sb0011110001111110;
    modelo_base_fixpt_b1_0[6] = 16'sb0011101000100010;
    modelo_base_fixpt_b1_0[7] = 16'sb0011010000100000;
    modelo_base_fixpt_b1_0[8] = 16'sb0100001000110100;
    modelo_base_fixpt_b1_0[9] = 16'sb1100110001011001;
    modelo_base_fixpt_b1_0[10] = 16'sb0000000000000000;
    modelo_base_fixpt_b1_0[11] = 16'sb1100011110111000;
    modelo_base_fixpt_b1_0[12] = 16'sb1100101110101000;
    modelo_base_fixpt_b1_0[13] = 16'sb0000010010010011;
    modelo_base_fixpt_b1_0[14] = 16'sb0011110101101000;
    modelo_base_fixpt_b1_0[15] = 16'sb1111100111011101;
    modelo_base_fixpt_w1[0] = 16'sb0010101110111011;
    modelo_base_fixpt_w1[1] = 16'sb0001111101100100;
    modelo_base_fixpt_w1[2] = 16'sb0000001110101001;
    modelo_base_fixpt_w1[3] = 16'sb1101100111011100;
    modelo_base_fixpt_w1[4] = 16'sb0001001101010000;
    modelo_base_fixpt_w1[5] = 16'sb0000101100100111;
    modelo_base_fixpt_w1[6] = 16'sb1011110011001001;
    modelo_base_fixpt_w1[7] = 16'sb1010101010100111;
    modelo_base_fixpt_w1[8] = 16'sb0010001100011011;
    modelo_base_fixpt_w1[9] = 16'sb0011101000100111;
    modelo_base_fixpt_w1[10] = 16'sb1110011001110010;
    modelo_base_fixpt_w1[11] = 16'sb0001010111001111;
    modelo_base_fixpt_w1[12] = 16'sb1110011101111001;
    modelo_base_fixpt_w1[13] = 16'sb1110000111011111;
    modelo_base_fixpt_w1[14] = 16'sb0000100111010110;
    modelo_base_fixpt_w1[15] = 16'sb1111100000000100;
    modelo_base_fixpt_w1[16] = 16'sb0001101001011010;
    modelo_base_fixpt_w1[17] = 16'sb1111110011010010;
    modelo_base_fixpt_w1[18] = 16'sb0100011110010100;
    modelo_base_fixpt_w1[19] = 16'sb0000100010001100;
    modelo_base_fixpt_w1[20] = 16'sb1111101110000111;
    modelo_base_fixpt_w1[21] = 16'sb0000111111001010;
    modelo_base_fixpt_w1[22] = 16'sb1100101001100001;
    modelo_base_fixpt_w1[23] = 16'sb1110111001101100;
    modelo_base_fixpt_w1[24] = 16'sb0011000100000111;
    modelo_base_fixpt_w1[25] = 16'sb1100101111000000;
    modelo_base_fixpt_w1[26] = 16'sb1011111001101100;
    modelo_base_fixpt_w1[27] = 16'sb1010111010101110;
    modelo_base_fixpt_w1[28] = 16'sb0001011010110001;
    modelo_base_fixpt_w1[29] = 16'sb0000001011101111;
    modelo_base_fixpt_w1[30] = 16'sb1110011010110100;
    modelo_base_fixpt_w1[31] = 16'sb1110110010000111;
    modelo_base_fixpt_w1[32] = 16'sb1110001011101000;
    modelo_base_fixpt_w1[33] = 16'sb0011010011110110;
    modelo_base_fixpt_w1[34] = 16'sb1110100110111101;
    modelo_base_fixpt_w1[35] = 16'sb1111111101110111;
    modelo_base_fixpt_w1[36] = 16'sb0010010001101111;
    modelo_base_fixpt_w1[37] = 16'sb0000110110100110;
    modelo_base_fixpt_w1[38] = 16'sb0010000100111001;
    modelo_base_fixpt_w1[39] = 16'sb0001001101001010;
    modelo_base_fixpt_w1[40] = 16'sb1111001001000010;
    modelo_base_fixpt_w1[41] = 16'sb1111010000011010;
    modelo_base_fixpt_w1[42] = 16'sb1111001000001110;
    modelo_base_fixpt_w1[43] = 16'sb0010100100110011;
    modelo_base_fixpt_w1[44] = 16'sb1111111101011011;
    modelo_base_fixpt_w1[45] = 16'sb1110111010010100;
    modelo_base_fixpt_w1[46] = 16'sb1111100011100011;
    modelo_base_fixpt_w1[47] = 16'sb1110100000111100;
    modelo_base_fixpt_w1[48] = 16'sb0001000010110000;
    modelo_base_fixpt_w1[49] = 16'sb0000010110011111;
    modelo_base_fixpt_w1[50] = 16'sb0000101111110100;
    modelo_base_fixpt_w1[51] = 16'sb0010011101011101;
    modelo_base_fixpt_w1[52] = 16'sb0010011111100101;
    modelo_base_fixpt_w1[53] = 16'sb0001010100000001;
    modelo_base_fixpt_w1[54] = 16'sb1110101001110101;
    modelo_base_fixpt_w1[55] = 16'sb0000110001000111;
    modelo_base_fixpt_w1[56] = 16'sb0010000001010101;
    modelo_base_fixpt_w1[57] = 16'sb0000110000000100;
    modelo_base_fixpt_w1[58] = 16'sb0100011000101100;
    modelo_base_fixpt_w1[59] = 16'sb0001010101000101;
    modelo_base_fixpt_w1[60] = 16'sb0001010100111111;
    modelo_base_fixpt_w1[61] = 16'sb0000001100001011;
    modelo_base_fixpt_w1[62] = 16'sb0001000111100101;
    modelo_base_fixpt_w1[63] = 16'sb1111101010111001;
    modelo_base_fixpt_w1[64] = 16'sb1110010000111101;
    modelo_base_fixpt_w1[65] = 16'sb0000100111001010;
    modelo_base_fixpt_w1[66] = 16'sb1100001110110010;
    modelo_base_fixpt_w1[67] = 16'sb0000001111110010;
    modelo_base_fixpt_w1[68] = 16'sb1110110001001000;
    modelo_base_fixpt_w1[69] = 16'sb0000011010110110;
    modelo_base_fixpt_w1[70] = 16'sb1111100010000001;
    modelo_base_fixpt_w1[71] = 16'sb1111011110101101;
    modelo_base_fixpt_w1[72] = 16'sb0000011011011001;
    modelo_base_fixpt_w1[73] = 16'sb1100101101001101;
    modelo_base_fixpt_w1[74] = 16'sb0000101111000001;
    modelo_base_fixpt_w1[75] = 16'sb1101101010001000;
    modelo_base_fixpt_w1[76] = 16'sb1101110000000101;
    modelo_base_fixpt_w1[77] = 16'sb0001111111011010;
    modelo_base_fixpt_w1[78] = 16'sb1111101010000000;
    modelo_base_fixpt_w1[79] = 16'sb0011000100111100;
    modelo_base_fixpt_w1[80] = 16'sb0001010010111011;
    modelo_base_fixpt_w1[81] = 16'sb0001000011010101;
    modelo_base_fixpt_w1[82] = 16'sb1100111110010000;
    modelo_base_fixpt_w1[83] = 16'sb1110010110111110;
    modelo_base_fixpt_w1[84] = 16'sb0001000101100111;
    modelo_base_fixpt_w1[85] = 16'sb0000100100001001;
    modelo_base_fixpt_w1[86] = 16'sb1101110110110110;
    modelo_base_fixpt_w1[87] = 16'sb0000110110111110;
    modelo_base_fixpt_w1[88] = 16'sb1111001000011010;
    modelo_base_fixpt_w1[89] = 16'sb0000010111101111;
    modelo_base_fixpt_w1[90] = 16'sb0001000100001100;
    modelo_base_fixpt_w1[91] = 16'sb0000001011001101;
    modelo_base_fixpt_w1[92] = 16'sb1111011110110110;
    modelo_base_fixpt_w1[93] = 16'sb0010011011000001;
    modelo_base_fixpt_w1[94] = 16'sb0001000110101010;
    modelo_base_fixpt_w1[95] = 16'sb0010110000010101;
    modelo_base_fixpt_w1[96] = 16'sb0000111011000001;
    modelo_base_fixpt_w1[97] = 16'sb0010110101100111;
    modelo_base_fixpt_w1[98] = 16'sb1111111000010011;
    modelo_base_fixpt_w1[99] = 16'sb1100000011011001;
    modelo_base_fixpt_w1[100] = 16'sb0010000100000011;
    modelo_base_fixpt_w1[101] = 16'sb0000110100011010;
    modelo_base_fixpt_w1[102] = 16'sb0000010101011100;
    modelo_base_fixpt_w1[103] = 16'sb0100001001011100;
    modelo_base_fixpt_w1[104] = 16'sb1101111010010010;
    modelo_base_fixpt_w1[105] = 16'sb0000110100011100;
    modelo_base_fixpt_w1[106] = 16'sb0001001100110000;
    modelo_base_fixpt_w1[107] = 16'sb1111100101011001;
    modelo_base_fixpt_w1[108] = 16'sb1101011010100000;
    modelo_base_fixpt_w1[109] = 16'sb1111011001111101;
    modelo_base_fixpt_w1[110] = 16'sb1111011110001100;
    modelo_base_fixpt_w1[111] = 16'sb0001011101011100;
    modelo_base_fixpt_w1[112] = 16'sb0010100111111011;
    modelo_base_fixpt_w1[113] = 16'sb0100011000011010;
    modelo_base_fixpt_w1[114] = 16'sb0000111111110100;
    modelo_base_fixpt_w1[115] = 16'sb0011011100000000;
    modelo_base_fixpt_w1[116] = 16'sb0101000111111000;
    modelo_base_fixpt_w1[117] = 16'sb0001000010011000;
    modelo_base_fixpt_w1[118] = 16'sb0010011001110111;
    modelo_base_fixpt_w1[119] = 16'sb1110110100100010;
    modelo_base_fixpt_w1[120] = 16'sb0000111011100001;
    modelo_base_fixpt_w1[121] = 16'sb0010000010101111;
    modelo_base_fixpt_w1[122] = 16'sb1111000010101110;
    modelo_base_fixpt_w1[123] = 16'sb1110001011000100;
    modelo_base_fixpt_w1[124] = 16'sb1111111101111011;
    modelo_base_fixpt_w1[125] = 16'sb0001010110100000;
    modelo_base_fixpt_w1[126] = 16'sb1111000010001001;
    modelo_base_fixpt_w1[127] = 16'sb1111011001011101;
    modelo_base_fixpt_w1[128] = 16'sb0000000110010000;
    modelo_base_fixpt_w1[129] = 16'sb0000010001111001;
    modelo_base_fixpt_w1[130] = 16'sb1110100001000010;
    modelo_base_fixpt_w1[131] = 16'sb0010111110010101;
    modelo_base_fixpt_w1[132] = 16'sb1100001001010110;
    modelo_base_fixpt_w1[133] = 16'sb1110101110110010;
    modelo_base_fixpt_w1[134] = 16'sb0010011110010111;
    modelo_base_fixpt_w1[135] = 16'sb1111001010110010;
    modelo_base_fixpt_w1[136] = 16'sb0001000010100101;
    modelo_base_fixpt_w1[137] = 16'sb1111100110001100;
    modelo_base_fixpt_w1[138] = 16'sb0011010110001111;
    modelo_base_fixpt_w1[139] = 16'sb0010101010110001;
    modelo_base_fixpt_w1[140] = 16'sb1100111101000000;
    modelo_base_fixpt_w1[141] = 16'sb0000110110100110;
    modelo_base_fixpt_w1[142] = 16'sb1101111110110011;
    modelo_base_fixpt_w1[143] = 16'sb0000000110010100;
    modelo_base_fixpt_w1[144] = 16'sb0000111100111111;
    modelo_base_fixpt_w1[145] = 16'sb1100010001110101;
    modelo_base_fixpt_w1[146] = 16'sb1110001100110010;
    modelo_base_fixpt_w1[147] = 16'sb1011111111000010;
    modelo_base_fixpt_w1[148] = 16'sb0001010111101111;
    modelo_base_fixpt_w1[149] = 16'sb0000100010111010;
    modelo_base_fixpt_w1[150] = 16'sb0000100101000111;
    modelo_base_fixpt_w1[151] = 16'sb0000110101010110;
    modelo_base_fixpt_w1[152] = 16'sb0010000010011110;
    modelo_base_fixpt_w1[153] = 16'sb1101010110000110;
    modelo_base_fixpt_w1[154] = 16'sb1111100000100010;
    modelo_base_fixpt_w1[155] = 16'sb1111001000011111;
    modelo_base_fixpt_w1[156] = 16'sb1100010000001011;
    modelo_base_fixpt_w1[157] = 16'sb1011110110011110;
    modelo_base_fixpt_w1[158] = 16'sb1111100111101110;
    modelo_base_fixpt_w1[159] = 16'sb0011111010001111;
    modelo_base_fixpt_w1[160] = 16'sb1110101010011101;
    modelo_base_fixpt_w1[161] = 16'sb1111100100000011;
    modelo_base_fixpt_w1[162] = 16'sb1111001011110001;
    modelo_base_fixpt_w1[163] = 16'sb1111101101011100;
    modelo_base_fixpt_w1[164] = 16'sb0010000010000010;
    modelo_base_fixpt_w1[165] = 16'sb0010111010100011;
    modelo_base_fixpt_w1[166] = 16'sb0000111100010000;
    modelo_base_fixpt_w1[167] = 16'sb0001011100011011;
    modelo_base_fixpt_w1[168] = 16'sb0001101010011011;
    modelo_base_fixpt_w1[169] = 16'sb1111011110010100;
    modelo_base_fixpt_w1[170] = 16'sb1111001111110000;
    modelo_base_fixpt_w1[171] = 16'sb0001000110111011;
    modelo_base_fixpt_w1[172] = 16'sb1110100010100101;
    modelo_base_fixpt_w1[173] = 16'sb0000000001111111;
    modelo_base_fixpt_w1[174] = 16'sb0000010000101010;
    modelo_base_fixpt_w1[175] = 16'sb1100010000100000;
    modelo_base_fixpt_w1[176] = 16'sb1110100011011000;
    modelo_base_fixpt_w1[177] = 16'sb1101010101010101;
    modelo_base_fixpt_w1[178] = 16'sb0010101111100110;
    modelo_base_fixpt_w1[179] = 16'sb1110010010000101;
    modelo_base_fixpt_w1[180] = 16'sb1111000010001110;
    modelo_base_fixpt_w1[181] = 16'sb0001011000011000;
    modelo_base_fixpt_w1[182] = 16'sb1111000011011100;
    modelo_base_fixpt_w1[183] = 16'sb1101100111011001;
    modelo_base_fixpt_w1[184] = 16'sb0011011011111111;
    modelo_base_fixpt_w1[185] = 16'sb1111001010001100;
    modelo_base_fixpt_w1[186] = 16'sb1101100101110011;
    modelo_base_fixpt_w1[187] = 16'sb1101000010100100;
    modelo_base_fixpt_w1[188] = 16'sb1110111101000000;
    modelo_base_fixpt_w1[189] = 16'sb0001100100011111;
    modelo_base_fixpt_w1[190] = 16'sb1110101011001111;
    modelo_base_fixpt_w1[191] = 16'sb0001000001110100;
    modelo_base_fixpt_w1[192] = 16'sb1110011010000011;
    modelo_base_fixpt_w1[193] = 16'sb1011010111001011;
    modelo_base_fixpt_w1[194] = 16'sb0011010111100101;
    modelo_base_fixpt_w1[195] = 16'sb1111100100111011;
    modelo_base_fixpt_w1[196] = 16'sb0000110011111111;
    modelo_base_fixpt_w1[197] = 16'sb0011100000000001;
    modelo_base_fixpt_w1[198] = 16'sb1111011011101000;
    modelo_base_fixpt_w1[199] = 16'sb0001111111001000;
    modelo_base_fixpt_w1[200] = 16'sb1110000011110001;
    modelo_base_fixpt_w1[201] = 16'sb1110001010000000;
    modelo_base_fixpt_w1[202] = 16'sb0000001010111110;
    modelo_base_fixpt_w1[203] = 16'sb1110101010111110;
    modelo_base_fixpt_w1[204] = 16'sb1110010110010001;
    modelo_base_fixpt_w1[205] = 16'sb0000111011101110;
    modelo_base_fixpt_w1[206] = 16'sb0000100101001011;
    modelo_base_fixpt_w1[207] = 16'sb0000000101100010;
    modelo_base_fixpt_w1[208] = 16'sb1101111101010000;
    modelo_base_fixpt_w1[209] = 16'sb0001110001101010;
    modelo_base_fixpt_w1[210] = 16'sb0010100001111110;
    modelo_base_fixpt_w1[211] = 16'sb1110110100000110;
    modelo_base_fixpt_w1[212] = 16'sb1101111011100110;
    modelo_base_fixpt_w1[213] = 16'sb1101110001000101;
    modelo_base_fixpt_w1[214] = 16'sb0001011001100011;
    modelo_base_fixpt_w1[215] = 16'sb1111111000010111;
    modelo_base_fixpt_w1[216] = 16'sb1111010100010011;
    modelo_base_fixpt_w1[217] = 16'sb1100011100001111;
    modelo_base_fixpt_w1[218] = 16'sb0000101011011000;
    modelo_base_fixpt_w1[219] = 16'sb0011101010110111;
    modelo_base_fixpt_w1[220] = 16'sb1101101010100101;
    modelo_base_fixpt_w1[221] = 16'sb0010011010110100;
    modelo_base_fixpt_w1[222] = 16'sb1111110110000101;
    modelo_base_fixpt_w1[223] = 16'sb1101110010100110;
    modelo_base_fixpt_w1[224] = 16'sb0010000101101110;
    modelo_base_fixpt_w1[225] = 16'sb0000011011110100;
    modelo_base_fixpt_w1[226] = 16'sb0000000101111100;
    modelo_base_fixpt_w1[227] = 16'sb0001101110011011;
    modelo_base_fixpt_w1[228] = 16'sb0011101001111000;
    modelo_base_fixpt_w1[229] = 16'sb0010000100001100;
    modelo_base_fixpt_w1[230] = 16'sb1110110000011010;
    modelo_base_fixpt_w1[231] = 16'sb0000010011110001;
    modelo_base_fixpt_w1[232] = 16'sb1101010101101010;
    modelo_base_fixpt_w1[233] = 16'sb1101110010100101;
    modelo_base_fixpt_w1[234] = 16'sb0001101101100001;
    modelo_base_fixpt_w1[235] = 16'sb1110011101010000;
    modelo_base_fixpt_w1[236] = 16'sb0000010110111000;
    modelo_base_fixpt_w1[237] = 16'sb1100010101110010;
    modelo_base_fixpt_w1[238] = 16'sb0000010010110101;
    modelo_base_fixpt_w1[239] = 16'sb1111100100011101;
    modelo_base_fixpt_w1[240] = 16'sb0011001011101001;
    modelo_base_fixpt_w1[241] = 16'sb1101001011011101;
    modelo_base_fixpt_w1[242] = 16'sb0000011111111011;
    modelo_base_fixpt_w1[243] = 16'sb0000111100101010;
    modelo_base_fixpt_w1[244] = 16'sb1110110100111010;
    modelo_base_fixpt_w1[245] = 16'sb0000100100111110;
    modelo_base_fixpt_w1[246] = 16'sb1101111111000100;
    modelo_base_fixpt_w1[247] = 16'sb1100101001110101;
    modelo_base_fixpt_w1[248] = 16'sb0000001110001001;
    modelo_base_fixpt_w1[249] = 16'sb0100000011010100;
    modelo_base_fixpt_w1[250] = 16'sb1100101110101100;
    modelo_base_fixpt_w1[251] = 16'sb1111111010001101;
    modelo_base_fixpt_w1[252] = 16'sb1100011101011110;
    modelo_base_fixpt_w1[253] = 16'sb1110001101010110;
    modelo_base_fixpt_w1[254] = 16'sb0001010111101110;
    modelo_base_fixpt_w1[255] = 16'sb1110011110110001;
    modelo_base_fixpt_w1[256] = 16'sb0001101100100001;
    modelo_base_fixpt_w1[257] = 16'sb0001011111011100;
    modelo_base_fixpt_w1[258] = 16'sb0010010010110101;
    modelo_base_fixpt_w1[259] = 16'sb0011111100111111;
    modelo_base_fixpt_w1[260] = 16'sb1110100001111111;
    modelo_base_fixpt_w1[261] = 16'sb1100010101000111;
    modelo_base_fixpt_w1[262] = 16'sb1101111110100111;
    modelo_base_fixpt_w1[263] = 16'sb0001001001010110;
    modelo_base_fixpt_w1[264] = 16'sb1111000101101101;
    modelo_base_fixpt_w1[265] = 16'sb1110100111110100;
    modelo_base_fixpt_w1[266] = 16'sb0001001001001101;
    modelo_base_fixpt_w1[267] = 16'sb1111011111011111;
    modelo_base_fixpt_w1[268] = 16'sb1110011001011010;
    modelo_base_fixpt_w1[269] = 16'sb0001101010011110;
    modelo_base_fixpt_w1[270] = 16'sb1111110010101101;
    modelo_base_fixpt_w1[271] = 16'sb0001001110011001;
    modelo_base_fixpt_w1[272] = 16'sb0000011001001011;
    modelo_base_fixpt_w1[273] = 16'sb0000110000000010;
    modelo_base_fixpt_w1[274] = 16'sb1110110011010011;
    modelo_base_fixpt_w1[275] = 16'sb0001010011100011;
    modelo_base_fixpt_w1[276] = 16'sb0000010101001001;
    modelo_base_fixpt_w1[277] = 16'sb0010011100110110;
    modelo_base_fixpt_w1[278] = 16'sb1111101100110010;
    modelo_base_fixpt_w1[279] = 16'sb1110111001100010;
    modelo_base_fixpt_w1[280] = 16'sb0101000111000001;
    modelo_base_fixpt_w1[281] = 16'sb0000110011011010;
    modelo_base_fixpt_w1[282] = 16'sb0100001001111110;
    modelo_base_fixpt_w1[283] = 16'sb0100110101111010;
    modelo_base_fixpt_w1[284] = 16'sb0000010001100101;
    modelo_base_fixpt_w1[285] = 16'sb1110010011111011;
    modelo_base_fixpt_w1[286] = 16'sb1101100011100000;
    modelo_base_fixpt_w1[287] = 16'sb1110100110001011;
    modelo_base_fixpt_w1[288] = 16'sb1111001010010000;
    modelo_base_fixpt_w1[289] = 16'sb1111001001101110;
    modelo_base_fixpt_w1[290] = 16'sb0010110000110110;
    modelo_base_fixpt_w1[291] = 16'sb1111101011000111;
    modelo_base_fixpt_w1[292] = 16'sb0011101010100111;
    modelo_base_fixpt_w1[293] = 16'sb0010100101011110;
    modelo_base_fixpt_w1[294] = 16'sb1111110010110011;
    modelo_base_fixpt_w1[295] = 16'sb0100011101101100;
    modelo_base_fixpt_w1[296] = 16'sb0010010001001011;
    modelo_base_fixpt_w1[297] = 16'sb0001001110110110;
    modelo_base_fixpt_w1[298] = 16'sb0010101011101000;
    modelo_base_fixpt_w1[299] = 16'sb0010011100101010;
    modelo_base_fixpt_w1[300] = 16'sb1110100000111110;
    modelo_base_fixpt_w1[301] = 16'sb0000011101100111;
    modelo_base_fixpt_w1[302] = 16'sb0001011101000110;
    modelo_base_fixpt_w1[303] = 16'sb0000010001000101;
    modelo_base_fixpt_w1[304] = 16'sb1110101011010101;
    modelo_base_fixpt_w1[305] = 16'sb1111100110101100;
    modelo_base_fixpt_w1[306] = 16'sb1111001010111001;
    modelo_base_fixpt_w1[307] = 16'sb1110110111011011;
    modelo_base_fixpt_w1[308] = 16'sb1110000001101111;
    modelo_base_fixpt_w1[309] = 16'sb0000001010101101;
    modelo_base_fixpt_w1[310] = 16'sb1101111000010100;
    modelo_base_fixpt_w1[311] = 16'sb1110101010111000;
    modelo_base_fixpt_w1[312] = 16'sb1110101011100100;
    modelo_base_fixpt_w1[313] = 16'sb0001100101101001;
    modelo_base_fixpt_w1[314] = 16'sb1110010011100010;
    modelo_base_fixpt_w1[315] = 16'sb0001010001110010;
    modelo_base_fixpt_w1[316] = 16'sb1110101101011100;
    modelo_base_fixpt_w1[317] = 16'sb0000010000110110;
    modelo_base_fixpt_w1[318] = 16'sb1110100000000011;
    modelo_base_fixpt_w1[319] = 16'sb0000111001000000;
    modelo_base_fixpt_w1[320] = 16'sb1110011001001001;
    modelo_base_fixpt_w1[321] = 16'sb1110010001001111;
    modelo_base_fixpt_w1[322] = 16'sb0010001101000011;
    modelo_base_fixpt_w1[323] = 16'sb1110100110100011;
    modelo_base_fixpt_w1[324] = 16'sb1111011001101101;
    modelo_base_fixpt_w1[325] = 16'sb1110111000100011;
    modelo_base_fixpt_w1[326] = 16'sb0010000010110110;
    modelo_base_fixpt_w1[327] = 16'sb1111001100111011;
    modelo_base_fixpt_w1[328] = 16'sb0010100111111011;
    modelo_base_fixpt_w1[329] = 16'sb1110101000110010;
    modelo_base_fixpt_w1[330] = 16'sb0010010000001100;
    modelo_base_fixpt_w1[331] = 16'sb0000100111001010;
    modelo_base_fixpt_w1[332] = 16'sb1111011011101011;
    modelo_base_fixpt_w1[333] = 16'sb0010101111001111;
    modelo_base_fixpt_w1[334] = 16'sb0001010110011000;
    modelo_base_fixpt_w1[335] = 16'sb0011011101011011;
    modelo_base_fixpt_w1[336] = 16'sb0101101000001000;
    modelo_base_fixpt_w1[337] = 16'sb0010001100101000;
    modelo_base_fixpt_w1[338] = 16'sb1111101010111111;
    modelo_base_fixpt_w1[339] = 16'sb1100010010111011;
    modelo_base_fixpt_w1[340] = 16'sb0101010101001110;
    modelo_base_fixpt_w1[341] = 16'sb0000001101100111;
    modelo_base_fixpt_w1[342] = 16'sb0011101001111001;
    modelo_base_fixpt_w1[343] = 16'sb0101110110010001;
    modelo_base_fixpt_w1[344] = 16'sb1110010011001000;
    modelo_base_fixpt_w1[345] = 16'sb1101100100111101;
    modelo_base_fixpt_w1[346] = 16'sb1111101111110001;
    modelo_base_fixpt_w1[347] = 16'sb1101110000100011;
    modelo_base_fixpt_w1[348] = 16'sb1101111110000000;
    modelo_base_fixpt_w1[349] = 16'sb1110000100010110;
    modelo_base_fixpt_w1[350] = 16'sb0011111010010101;
    modelo_base_fixpt_w1[351] = 16'sb0011010011111100;
    modelo_base_fixpt_w1[352] = 16'sb1111100110000011;
    modelo_base_fixpt_w1[353] = 16'sb0011100010110110;
    modelo_base_fixpt_w1[354] = 16'sb1111111110101111;
    modelo_base_fixpt_w1[355] = 16'sb0001010110001000;
    modelo_base_fixpt_w1[356] = 16'sb0100100000001010;
    modelo_base_fixpt_w1[357] = 16'sb0100011011001000;
    modelo_base_fixpt_w1[358] = 16'sb1111001101100000;
    modelo_base_fixpt_w1[359] = 16'sb0000110010111100;
    modelo_base_fixpt_w1[360] = 16'sb1111100111101001;
    modelo_base_fixpt_w1[361] = 16'sb0010110101010010;
    modelo_base_fixpt_w1[362] = 16'sb1101110110101100;
    modelo_base_fixpt_w1[363] = 16'sb0100010101101111;
    modelo_base_fixpt_w1[364] = 16'sb1111001100110110;
    modelo_base_fixpt_w1[365] = 16'sb0001100001011000;
    modelo_base_fixpt_w1[366] = 16'sb0010010111001111;
    modelo_base_fixpt_w1[367] = 16'sb0001010001100110;
    modelo_base_fixpt_w1[368] = 16'sb1110011110111010;
    modelo_base_fixpt_w1[369] = 16'sb1100000000011100;
    modelo_base_fixpt_w1[370] = 16'sb0101011111011010;
    modelo_base_fixpt_w1[371] = 16'sb0000010110010011;
    modelo_base_fixpt_w1[372] = 16'sb0010100010110000;
    modelo_base_fixpt_w1[373] = 16'sb0011000110101011;
    modelo_base_fixpt_w1[374] = 16'sb1100100110100101;
    modelo_base_fixpt_w1[375] = 16'sb1101011000000011;
    modelo_base_fixpt_w1[376] = 16'sb0001001100101001;
    modelo_base_fixpt_w1[377] = 16'sb0011001000010110;
    modelo_base_fixpt_w1[378] = 16'sb0000101010100011;
    modelo_base_fixpt_w1[379] = 16'sb1101111101010011;
    modelo_base_fixpt_w1[380] = 16'sb0001100100101001;
    modelo_base_fixpt_w1[381] = 16'sb0010000011010000;
    modelo_base_fixpt_w1[382] = 16'sb0001011111111110;
    modelo_base_fixpt_w1[383] = 16'sb0011011100110000;
    modelo_base_fixpt_w1[384] = 16'sb0000101001110010;
    modelo_base_fixpt_w1[385] = 16'sb0000011011001011;
    modelo_base_fixpt_w1[386] = 16'sb0101010001000111;
    modelo_base_fixpt_w1[387] = 16'sb0000110101100101;
    modelo_base_fixpt_w1[388] = 16'sb0011000010011011;
    modelo_base_fixpt_w1[389] = 16'sb0010111110001011;
    modelo_base_fixpt_w1[390] = 16'sb0001110110011011;
    modelo_base_fixpt_w1[391] = 16'sb0000011110000101;
    modelo_base_fixpt_w1[392] = 16'sb1111101100010100;
    modelo_base_fixpt_w1[393] = 16'sb1110110010110110;
    modelo_base_fixpt_w1[394] = 16'sb1110100010101010;
    modelo_base_fixpt_w1[395] = 16'sb0001110001111110;
    modelo_base_fixpt_w1[396] = 16'sb0010100000101100;
    modelo_base_fixpt_w1[397] = 16'sb1111010111101011;
    modelo_base_fixpt_w1[398] = 16'sb1101001001100100;
    modelo_base_fixpt_w1[399] = 16'sb1111100111100101;
    modelo_base_fixpt_w1[400] = 16'sb1100110100011110;
    modelo_base_fixpt_w1[401] = 16'sb1101011100000000;
    modelo_base_fixpt_w1[402] = 16'sb1110101010010111;
    modelo_base_fixpt_w1[403] = 16'sb1100110001011001;
    modelo_base_fixpt_w1[404] = 16'sb1101101000100001;
    modelo_base_fixpt_w1[405] = 16'sb0010111010101101;
    modelo_base_fixpt_w1[406] = 16'sb0000001011101010;
    modelo_base_fixpt_w1[407] = 16'sb0010000001100100;
    modelo_base_fixpt_w1[408] = 16'sb1101101010010111;
    modelo_base_fixpt_w1[409] = 16'sb0010100100110010;
    modelo_base_fixpt_w1[410] = 16'sb1111110100011010;
    modelo_base_fixpt_w1[411] = 16'sb1111100011101000;
    modelo_base_fixpt_w1[412] = 16'sb0010011110000100;
    modelo_base_fixpt_w1[413] = 16'sb0001110100011001;
    modelo_base_fixpt_w1[414] = 16'sb1101001000011101;
    modelo_base_fixpt_w1[415] = 16'sb0000111011011101;
    modelo_base_fixpt_w1[416] = 16'sb0001010111011100;
    modelo_base_fixpt_w1[417] = 16'sb1110100000111010;
    modelo_base_fixpt_w1[418] = 16'sb0000011111011000;
    modelo_base_fixpt_w1[419] = 16'sb0010110111111000;
    modelo_base_fixpt_w1[420] = 16'sb0001100100011111;
    modelo_base_fixpt_w1[421] = 16'sb0000011110001110;
    modelo_base_fixpt_w1[422] = 16'sb0000011100001001;
    modelo_base_fixpt_w1[423] = 16'sb0000010111001111;
    modelo_base_fixpt_w1[424] = 16'sb0001101110001100;
    modelo_base_fixpt_w1[425] = 16'sb1100100000001010;
    modelo_base_fixpt_w1[426] = 16'sb1101100011110001;
    modelo_base_fixpt_w1[427] = 16'sb1111010001110001;
    modelo_base_fixpt_w1[428] = 16'sb0011100000011000;
    modelo_base_fixpt_w1[429] = 16'sb0010101111110011;
    modelo_base_fixpt_w1[430] = 16'sb1011101100110011;
    modelo_base_fixpt_w1[431] = 16'sb0000000101001111;
    modelo_base_fixpt_w1[432] = 16'sb1100001110010111;
    modelo_base_fixpt_w1[433] = 16'sb1011100011111001;
    modelo_base_fixpt_w1[434] = 16'sb1111000001000011;
    modelo_base_fixpt_w1[435] = 16'sb0010110010110110;
    modelo_base_fixpt_w1[436] = 16'sb1111111010011001;
    modelo_base_fixpt_w1[437] = 16'sb0000011001010100;
    modelo_base_fixpt_w1[438] = 16'sb0001010010000011;
    modelo_base_fixpt_w1[439] = 16'sb0000011000111110;
    modelo_base_fixpt_w1[440] = 16'sb1111011100100011;
    modelo_base_fixpt_w1[441] = 16'sb1101110110011100;
    modelo_base_fixpt_w1[442] = 16'sb1110110011110100;
    modelo_base_fixpt_w1[443] = 16'sb1100001011100100;
    modelo_base_fixpt_w1[444] = 16'sb0001010001100000;
    modelo_base_fixpt_w1[445] = 16'sb0000001011010011;
    modelo_base_fixpt_w1[446] = 16'sb1110101000011100;
    modelo_base_fixpt_w1[447] = 16'sb1101101100111010;
    modelo_base_fixpt_w1[448] = 16'sb1110011000001010;
    modelo_base_fixpt_w1[449] = 16'sb1111000100010000;
    modelo_base_fixpt_w1[450] = 16'sb1111001011000110;
    modelo_base_fixpt_w1[451] = 16'sb0001011101010010;
    modelo_base_fixpt_w1[452] = 16'sb1111011000101101;
    modelo_base_fixpt_w1[453] = 16'sb1101010110010001;
    modelo_base_fixpt_w1[454] = 16'sb1100111101101111;
    modelo_base_fixpt_w1[455] = 16'sb1110111001111100;
    modelo_base_fixpt_w1[456] = 16'sb1110011111001000;
    modelo_base_fixpt_w1[457] = 16'sb0001001001001010;
    modelo_base_fixpt_w1[458] = 16'sb1111111000000101;
    modelo_base_fixpt_w1[459] = 16'sb0001001001110100;
    modelo_base_fixpt_w1[460] = 16'sb0000011110011010;
    modelo_base_fixpt_w1[461] = 16'sb1111011000111011;
    modelo_base_fixpt_w1[462] = 16'sb1110010000110101;
    modelo_base_fixpt_w1[463] = 16'sb0001011111001110;
    modelo_base_fixpt_w1[464] = 16'sb0001010010000001;
    modelo_base_fixpt_w1[465] = 16'sb0010010110101110;
    modelo_base_fixpt_w1[466] = 16'sb1111001010010001;
    modelo_base_fixpt_w1[467] = 16'sb1111101111001111;
    modelo_base_fixpt_w1[468] = 16'sb0001011011110111;
    modelo_base_fixpt_w1[469] = 16'sb0000100111101001;
    modelo_base_fixpt_w1[470] = 16'sb1111101101100110;
    modelo_base_fixpt_w1[471] = 16'sb1110110000110010;
    modelo_base_fixpt_w1[472] = 16'sb1101011100110011;
    modelo_base_fixpt_w1[473] = 16'sb0000000001101111;
    modelo_base_fixpt_w1[474] = 16'sb1110011011010101;
    modelo_base_fixpt_w1[475] = 16'sb0001001000111110;
    modelo_base_fixpt_w1[476] = 16'sb0001110000110110;
    modelo_base_fixpt_w1[477] = 16'sb1101010000001101;
    modelo_base_fixpt_w1[478] = 16'sb1111011011010100;
    modelo_base_fixpt_w1[479] = 16'sb0000001110100010;
    modelo_base_fixpt_tmp_1 = 16'b0000000000000000;
    modelo_base_fixpt_acum_2 = 16'sb0000000000000000;
    modelo_base_fixpt_div_temp = 44'sh00000000000;
    modelo_base_fixpt_cast_0 = 17'sb00000000000000000;
    modelo_base_fixpt_slice_cast_0 = 44'sh00000000000;
    modelo_base_fixpt_acum_1 = 16'sb0000000000000000;
    modelo_base_fixpt_cast = 17'sb00000000000000000;
    modelo_base_fixpt_slice_cast = 44'sh00000000000;
    modelo_base_fixpt_cast_4 = 44'sh00000000000;
    //HDL code generation from MATLAB function: modelo_base_fixpt
    //%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    //                                                                          %
    //          Generated by MATLAB 9.13 and Fixed-Point Designer 7.5           %
    //                                                                          %
    //%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    // Definición de Pesos y Biases
    // Capa oculta
    // Capa de salida
    modelo_base_fixpt_acum = 16'sb0000000000000000;

    for(modelo_base_fixpt_i = 32'sd0; modelo_base_fixpt_i <= 32'sd15; modelo_base_fixpt_i = modelo_base_fixpt_i + 32'sd1) begin
      modelo_base_fixpt_acum_2 = 16'sb0000000000000000;

      for(modelo_base_fixpt_i_0 = 32'sd0; modelo_base_fixpt_i_0 <= 32'sd29; modelo_base_fixpt_i_0 = modelo_base_fixpt_i_0 + 32'sd1) begin
        modelo_base_fixpt_add_cast_2[modelo_base_fixpt_i_0] = {modelo_base_fixpt_acum_2[15], {modelo_base_fixpt_acum_2, 17'b00000000000000000}};
        modelo_base_fixpt_cast_1[modelo_base_fixpt_i_0] = {1'b0, in[modelo_base_fixpt_i_0]};
        modelo_base_fixpt_mul_temp[modelo_base_fixpt_i_0] = modelo_base_fixpt_cast_1[modelo_base_fixpt_i_0] * modelo_base_fixpt_w1[modelo_base_fixpt_i_0 + (32'sd30 * modelo_base_fixpt_i)];
        modelo_base_fixpt_add_cast_3[modelo_base_fixpt_i_0] = modelo_base_fixpt_mul_temp[modelo_base_fixpt_i_0][31:0];
        modelo_base_fixpt_add_cast_4[modelo_base_fixpt_i_0] = {{2{modelo_base_fixpt_add_cast_3[modelo_base_fixpt_i_0][31]}}, modelo_base_fixpt_add_cast_3[modelo_base_fixpt_i_0]};
        modelo_base_fixpt_add_temp_0[modelo_base_fixpt_i_0] = modelo_base_fixpt_add_cast_2[modelo_base_fixpt_i_0] + modelo_base_fixpt_add_cast_4[modelo_base_fixpt_i_0];
        modelo_base_fixpt_acum_2 = modelo_base_fixpt_add_temp_0[modelo_base_fixpt_i_0][32:17];
      end

      modelo_base_fixpt_add_cast_0[modelo_base_fixpt_i] = {modelo_base_fixpt_acum_2[15], {modelo_base_fixpt_acum_2, 2'b00}};
      modelo_base_fixpt_add_cast_1[modelo_base_fixpt_i] = {{3{modelo_base_fixpt_b1_0[modelo_base_fixpt_i][15]}}, modelo_base_fixpt_b1_0[modelo_base_fixpt_i]};
      modelo_base_fixpt_add_temp[modelo_base_fixpt_i] = modelo_base_fixpt_add_cast_0[modelo_base_fixpt_i] + modelo_base_fixpt_add_cast_1[modelo_base_fixpt_i];
      modelo_base_fixpt_acum_1 = modelo_base_fixpt_add_temp[modelo_base_fixpt_i][17:2];
      if (modelo_base_fixpt_acum_1 < 16'sb0000000000000000) begin
        modelo_base_fixpt_tmp_1 = 16'b0000000000000000;
      end
      else begin
        modelo_base_fixpt_tmp_1 = {modelo_base_fixpt_acum_1[14:0], 1'b0};
      end
      modelo_base_fixpt_add_cast_5[modelo_base_fixpt_i] = {modelo_base_fixpt_acum[15], {modelo_base_fixpt_acum, 16'b0000000000000000}};
      modelo_base_fixpt_cast_3[modelo_base_fixpt_i] = {1'b0, modelo_base_fixpt_tmp_1};
      modelo_base_fixpt_mul_temp_0[modelo_base_fixpt_i] = modelo_base_fixpt_cast_3[modelo_base_fixpt_i] * modelo_base_fixpt_w[modelo_base_fixpt_i];
      modelo_base_fixpt_add_cast_6[modelo_base_fixpt_i] = modelo_base_fixpt_mul_temp_0[modelo_base_fixpt_i][31:0];
      modelo_base_fixpt_add_cast_7[modelo_base_fixpt_i] = {modelo_base_fixpt_add_cast_6[modelo_base_fixpt_i][31], modelo_base_fixpt_add_cast_6[modelo_base_fixpt_i]};
      modelo_base_fixpt_add_temp_1[modelo_base_fixpt_i] = modelo_base_fixpt_add_cast_5[modelo_base_fixpt_i] + modelo_base_fixpt_add_cast_7[modelo_base_fixpt_i];
      modelo_base_fixpt_acum = modelo_base_fixpt_add_temp_1[modelo_base_fixpt_i][31:16];
    end

    modelo_base_fixpt_t_0 = 21'sb111111010111001010101;
    modelo_base_fixpt_add_cast = modelo_base_fixpt_t_0[19:4];
    modelo_base_fixpt_acum_0 = modelo_base_fixpt_acum + modelo_base_fixpt_add_cast;
    if (modelo_base_fixpt_acum_0 < 16'sb0000000000000000) begin
      modelo_base_fixpt_cast = {modelo_base_fixpt_acum_0[15], modelo_base_fixpt_acum_0};
      modelo_base_fixpt_cast_0 =  - (modelo_base_fixpt_cast);
      modelo_base_fixpt_tmp = modelo_base_fixpt_cast_0[15:0];
    end
    else begin
      modelo_base_fixpt_tmp = modelo_base_fixpt_acum_0;
    end
    modelo_base_fixpt_cast_2 = {{2{modelo_base_fixpt_acum_0[15]}}, {modelo_base_fixpt_acum_0, 15'b000000000000000}};
    modelo_base_fixpt_a1 = modelo_base_fixpt_cast_2[31:0];
    if (modelo_base_fixpt_a1 < 32'sb00000000000000000000000000000000) begin
      modelo_base_fixpt_tmp_0 = 50'sh2000000000000;
    end
    else begin
      modelo_base_fixpt_tmp_0 = 50'sh1FFFFFFFFFFFF;
    end
    modelo_base_fixpt_add_cast_8 = {{2{modelo_base_fixpt_tmp[15]}}, modelo_base_fixpt_tmp};
    modelo_base_fixpt_b1 = modelo_base_fixpt_add_cast_8 + 18'sb000001000000000000;
    if ( ! (modelo_base_fixpt_b1 == 18'sb000000000000000000)) begin
      modelo_base_fixpt_slice_cast = {modelo_base_fixpt_a1, 12'b000000000000};
      if (modelo_base_fixpt_slice_cast[43] == modelo_base_fixpt_b1[17]) begin
        modelo_base_fixpt_slice_cast_0 = 44'sh7FFFFFFFFFF;
      end
      else begin
        modelo_base_fixpt_slice_cast_0 = 44'sh80000000000;
      end
      modelo_base_fixpt_cast_4 = {modelo_base_fixpt_a1, 12'b000000000000};
      if (modelo_base_fixpt_b1 == 31'sd0) begin
        modelo_base_fixpt_div_temp = modelo_base_fixpt_slice_cast_0;
      end
      else begin
        modelo_base_fixpt_div_temp = modelo_base_fixpt_cast_4 / modelo_base_fixpt_b1;
      end
      modelo_base_fixpt_tmp_0 = {{6{modelo_base_fixpt_div_temp[43]}}, modelo_base_fixpt_div_temp};
    end
    //     y = sigmoide(acum);
    // y = 0.4*tanh(acum) + 0.5;
    modelo_base_fixpt_add_cast_9 = {{2{modelo_base_fixpt_tmp_0[49]}}, modelo_base_fixpt_tmp_0};
    modelo_base_fixpt_add_temp_2 = modelo_base_fixpt_add_cast_9 + 52'sh0000008000000;
    modelo_base_fixpt_cast_5 = modelo_base_fixpt_add_temp_2[27:12];
    if (modelo_base_fixpt_cast_5 >= 16'b1000000000000000) begin
      out_1 = 1'b1;
    end
    else begin
      out_1 = 1'b0;
    end
  end



  assign out = out_1;

endmodule  // modelo_base_fixpt

