// -------------------------------------------------------------
// 
// File Name: C:\Users\juand\Documents\MATLAB\Resultados\modelo_podado\modelo_podado_hdl\modelo_podado\hdlsrc\modelo_podado_fixpt.v
// Created: 2022-12-10 22:01:23
// 
// Generated by MATLAB 9.13, MATLAB Coder 5.5 and HDL Coder 4.0
// 
// 
// 
// -- -------------------------------------------------------------
// -- Rate and Clocking Details
// -- -------------------------------------------------------------
// Design base rate: 1
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: modelo_podado_fixpt
// Source Path: modelo_podado_fixpt
// Hierarchy Level: 0
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module modelo_podado_fixpt
          (in_0,
           in_1,
           in_2,
           in_3,
           in_4,
           in_5,
           in_6,
           in_7,
           in_8,
           in_9,
           in_10,
           in_11,
           in_12,
           in_13,
           in_14,
           in_15,
           in_16,
           in_17,
           in_18,
           in_19,
           in_20,
           in_21,
           in_22,
           in_23,
           in_24,
           in_25,
           in_26,
           in_27,
           in_28,
           in_29,
           out);


  input   [15:0] in_0;  // ufix16_En15
  input   [15:0] in_1;  // ufix16_En15
  input   [15:0] in_2;  // ufix16_En15
  input   [15:0] in_3;  // ufix16_En15
  input   [15:0] in_4;  // ufix16_En15
  input   [15:0] in_5;  // ufix16_En15
  input   [15:0] in_6;  // ufix16_En15
  input   [15:0] in_7;  // ufix16_En15
  input   [15:0] in_8;  // ufix16_En15
  input   [15:0] in_9;  // ufix16_En15
  input   [15:0] in_10;  // ufix16_En15
  input   [15:0] in_11;  // ufix16_En15
  input   [15:0] in_12;  // ufix16_En15
  input   [15:0] in_13;  // ufix16_En15
  input   [15:0] in_14;  // ufix16_En15
  input   [15:0] in_15;  // ufix16_En15
  input   [15:0] in_16;  // ufix16_En15
  input   [15:0] in_17;  // ufix16_En15
  input   [15:0] in_18;  // ufix16_En15
  input   [15:0] in_19;  // ufix16_En15
  input   [15:0] in_20;  // ufix16_En15
  input   [15:0] in_21;  // ufix16_En15
  input   [15:0] in_22;  // ufix16_En15
  input   [15:0] in_23;  // ufix16_En15
  input   [15:0] in_24;  // ufix16_En15
  input   [15:0] in_25;  // ufix16_En15
  input   [15:0] in_26;  // ufix16_En15
  input   [15:0] in_27;  // ufix16_En15
  input   [15:0] in_28;  // ufix16_En15
  input   [15:0] in_29;  // ufix16_En15
  output  out;  // ufix1


  wire [15:0] in [0:29];  // ufix16_En15 [30]
  reg  out_1;  // ufix1
  reg signed [15:0] modelo_podado_fixpt_acum;  // sfix16_En12
  reg signed [15:0] modelo_podado_fixpt_acum_0;  // sfix16_En12
  reg signed [15:0] modelo_podado_fixpt_tmp;  // sfix16_En12
  reg signed [31:0] modelo_podado_fixpt_a1;  // sfix32_En28
  reg signed [49:0] modelo_podado_fixpt_tmp_0;  // sfix50_En28
  reg signed [17:0] modelo_podado_fixpt_b1;  // sfix18_En12
  reg [15:0] modelo_podado_fixpt_tmp_1;  // ufix16_En14
  reg signed [15:0] modelo_podado_fixpt_acum_1;  // sfix16_En13
  reg signed [15:0] modelo_podado_fixpt_acum_2;  // sfix16_En13
  reg signed [31:0] modelo_podado_fixpt_i;  // int32
  reg signed [31:0] modelo_podado_fixpt_i_0;  // int32
  reg signed [15:0] modelo_podado_fixpt_w [0:15];  // sfix16_En14 [16]
  reg signed [15:0] modelo_podado_fixpt_b1_0 [0:15];  // sfix16_En15 [16]
  reg signed [15:0] modelo_podado_fixpt_w1 [0:479];  // sfix16_En15 [480]
  reg signed [43:0] modelo_podado_fixpt_div_temp;  // sfix44_En28
  reg signed [20:0] modelo_podado_fixpt_t_0;  // sfix21_En16
  reg signed [15:0] modelo_podado_fixpt_add_cast;  // sfix16_En12
  reg signed [16:0] modelo_podado_fixpt_cast;  // sfix17_En12
  reg signed [16:0] modelo_podado_fixpt_cast_0;  // sfix17_En12
  reg signed [18:0] modelo_podado_fixpt_add_cast_0 [0:15];  // sfix19_En15 [16]
  reg signed [18:0] modelo_podado_fixpt_add_cast_1 [0:15];  // sfix19_En15 [16]
  reg signed [18:0] modelo_podado_fixpt_add_temp [0:15];  // sfix19_En15 [16]
  reg signed [33:0] modelo_podado_fixpt_add_cast_2 [0:29];  // sfix34_En30 [30]
  reg signed [16:0] modelo_podado_fixpt_cast_1 [0:29];  // sfix17_En15 [30]
  reg signed [32:0] modelo_podado_fixpt_mul_temp [0:29];  // sfix33_En30 [30]
  reg signed [31:0] modelo_podado_fixpt_add_cast_3 [0:29];  // sfix32_En30 [30]
  reg signed [33:0] modelo_podado_fixpt_add_cast_4 [0:29];  // sfix34_En30 [30]
  reg signed [33:0] modelo_podado_fixpt_add_temp_0 [0:29];  // sfix34_En30 [30]
  reg signed [32:0] modelo_podado_fixpt_cast_2;  // sfix33_En28
  reg signed [32:0] modelo_podado_fixpt_add_cast_5 [0:15];  // sfix33_En28 [16]
  reg signed [16:0] modelo_podado_fixpt_cast_3 [0:15];  // sfix17_En14 [16]
  reg signed [32:0] modelo_podado_fixpt_mul_temp_0 [0:15];  // sfix33_En28 [16]
  reg signed [31:0] modelo_podado_fixpt_add_cast_6 [0:15];  // sfix32_En28 [16]
  reg signed [32:0] modelo_podado_fixpt_add_cast_7 [0:15];  // sfix33_En28 [16]
  reg signed [32:0] modelo_podado_fixpt_add_temp_1 [0:15];  // sfix33_En28 [16]
  reg signed [17:0] modelo_podado_fixpt_add_cast_8;  // sfix18_En12
  reg signed [43:0] modelo_podado_fixpt_slice_cast;  // sfix44_En40
  reg signed [43:0] modelo_podado_fixpt_slice_cast_0;  // sfix44_En28
  reg signed [43:0] modelo_podado_fixpt_cast_4;  // sfix44_En40
  reg signed [51:0] modelo_podado_fixpt_add_cast_9;  // sfix52_En28
  reg signed [51:0] modelo_podado_fixpt_add_temp_2;  // sfix52_En28
  reg [15:0] modelo_podado_fixpt_cast_5;  // ufix16_En16


  assign in[0] = in_0;
  assign in[1] = in_1;
  assign in[2] = in_2;
  assign in[3] = in_3;
  assign in[4] = in_4;
  assign in[5] = in_5;
  assign in[6] = in_6;
  assign in[7] = in_7;
  assign in[8] = in_8;
  assign in[9] = in_9;
  assign in[10] = in_10;
  assign in[11] = in_11;
  assign in[12] = in_12;
  assign in[13] = in_13;
  assign in[14] = in_14;
  assign in[15] = in_15;
  assign in[16] = in_16;
  assign in[17] = in_17;
  assign in[18] = in_18;
  assign in[19] = in_19;
  assign in[20] = in_20;
  assign in[21] = in_21;
  assign in[22] = in_22;
  assign in[23] = in_23;
  assign in[24] = in_24;
  assign in[25] = in_25;
  assign in[26] = in_26;
  assign in[27] = in_27;
  assign in[28] = in_28;
  assign in[29] = in_29;

  always @* begin
    modelo_podado_fixpt_w[0] = 16'sb0000000000000000;
    modelo_podado_fixpt_w[1] = 16'sb0000000000000000;
    modelo_podado_fixpt_w[2] = 16'sb0000000000000000;
    modelo_podado_fixpt_w[3] = 16'sb0101011011001010;
    modelo_podado_fixpt_w[4] = 16'sb1010011110000001;
    modelo_podado_fixpt_w[5] = 16'sb1001101111000110;
    modelo_podado_fixpt_w[6] = 16'sb1010011000101010;
    modelo_podado_fixpt_w[7] = 16'sb0000000000000000;
    modelo_podado_fixpt_w[8] = 16'sb1001001001001100;
    modelo_podado_fixpt_w[9] = 16'sb0000000000000000;
    modelo_podado_fixpt_w[10] = 16'sb0000000000000000;
    modelo_podado_fixpt_w[11] = 16'sb0000000000000000;
    modelo_podado_fixpt_w[12] = 16'sb0101110001100101;
    modelo_podado_fixpt_w[13] = 16'sb0000000000000000;
    modelo_podado_fixpt_w[14] = 16'sb0000000000000000;
    modelo_podado_fixpt_w[15] = 16'sb0000000000000000;
    modelo_podado_fixpt_b1_0[0] = 16'sb0100010100010111;
    modelo_podado_fixpt_b1_0[1] = 16'sb1101100110110100;
    modelo_podado_fixpt_b1_0[2] = 16'sb0010101100001110;
    modelo_podado_fixpt_b1_0[3] = 16'sb1011101100111110;
    modelo_podado_fixpt_b1_0[4] = 16'sb0100110010101011;
    modelo_podado_fixpt_b1_0[5] = 16'sb0100111110000101;
    modelo_podado_fixpt_b1_0[6] = 16'sb0101011001111011;
    modelo_podado_fixpt_b1_0[7] = 16'sb0011111011001110;
    modelo_podado_fixpt_b1_0[8] = 16'sb0101110001101000;
    modelo_podado_fixpt_b1_0[9] = 16'sb1011010101011111;
    modelo_podado_fixpt_b1_0[10] = 16'sb0000000000000000;
    modelo_podado_fixpt_b1_0[11] = 16'sb1100000111111111;
    modelo_podado_fixpt_b1_0[12] = 16'sb1011010111000011;
    modelo_podado_fixpt_b1_0[13] = 16'sb0000100010100001;
    modelo_podado_fixpt_b1_0[14] = 16'sb0100000111010000;
    modelo_podado_fixpt_b1_0[15] = 16'sb1111100111011101;
    modelo_podado_fixpt_w1[0] = 16'sb0010110110011011;
    modelo_podado_fixpt_w1[1] = 16'sb0000000000000000;
    modelo_podado_fixpt_w1[2] = 16'sb0000000000000000;
    modelo_podado_fixpt_w1[3] = 16'sb1101101001010001;
    modelo_podado_fixpt_w1[4] = 16'sb0000000000000000;
    modelo_podado_fixpt_w1[5] = 16'sb0000000000000000;
    modelo_podado_fixpt_w1[6] = 16'sb1011100010101100;
    modelo_podado_fixpt_w1[7] = 16'sb1010010111101100;
    modelo_podado_fixpt_w1[8] = 16'sb0010010000100010;
    modelo_podado_fixpt_w1[9] = 16'sb0011101100001010;
    modelo_podado_fixpt_w1[10] = 16'sb1101111111101000;
    modelo_podado_fixpt_w1[11] = 16'sb0000000000000000;
    modelo_podado_fixpt_w1[12] = 16'sb0000000000000000;
    modelo_podado_fixpt_w1[13] = 16'sb1101101010011011;
    modelo_podado_fixpt_w1[14] = 16'sb0000000000000000;
    modelo_podado_fixpt_w1[15] = 16'sb0000000000000000;
    modelo_podado_fixpt_w1[16] = 16'sb0000000000000000;
    modelo_podado_fixpt_w1[17] = 16'sb0000000000000000;
    modelo_podado_fixpt_w1[18] = 16'sb0100011110010101;
    modelo_podado_fixpt_w1[19] = 16'sb0000000000000000;
    modelo_podado_fixpt_w1[20] = 16'sb0000000000000000;
    modelo_podado_fixpt_w1[21] = 16'sb0000000000000000;
    modelo_podado_fixpt_w1[22] = 16'sb1100101011001001;
    modelo_podado_fixpt_w1[23] = 16'sb0000000000000000;
    modelo_podado_fixpt_w1[24] = 16'sb0010111011111010;
    modelo_podado_fixpt_w1[25] = 16'sb1100110000010100;
    modelo_podado_fixpt_w1[26] = 16'sb1011110100110111;
    modelo_podado_fixpt_w1[27] = 16'sb1010110110001011;
    modelo_podado_fixpt_w1[28] = 16'sb0000000000000000;
    modelo_podado_fixpt_w1[29] = 16'sb0000000000000000;
    modelo_podado_fixpt_w1[30] = 16'sb0000000000000000;
    modelo_podado_fixpt_w1[31] = 16'sb0000000000000000;
    modelo_podado_fixpt_w1[32] = 16'sb0000000000000000;
    modelo_podado_fixpt_w1[33] = 16'sb0011101010001100;
    modelo_podado_fixpt_w1[34] = 16'sb0000000000000000;
    modelo_podado_fixpt_w1[35] = 16'sb0000000000000000;
    modelo_podado_fixpt_w1[36] = 16'sb0011000000101000;
    modelo_podado_fixpt_w1[37] = 16'sb0000000000000000;
    modelo_podado_fixpt_w1[38] = 16'sb0010000000101001;
    modelo_podado_fixpt_w1[39] = 16'sb0000000000000000;
    modelo_podado_fixpt_w1[40] = 16'sb0000000000000000;
    modelo_podado_fixpt_w1[41] = 16'sb0000000000000000;
    modelo_podado_fixpt_w1[42] = 16'sb0000000000000000;
    modelo_podado_fixpt_w1[43] = 16'sb0011110001100000;
    modelo_podado_fixpt_w1[44] = 16'sb0000000000000000;
    modelo_podado_fixpt_w1[45] = 16'sb0000000000000000;
    modelo_podado_fixpt_w1[46] = 16'sb0000000000000000;
    modelo_podado_fixpt_w1[47] = 16'sb0000000000000000;
    modelo_podado_fixpt_w1[48] = 16'sb0000000000000000;
    modelo_podado_fixpt_w1[49] = 16'sb0000000000000000;
    modelo_podado_fixpt_w1[50] = 16'sb0000000000000000;
    modelo_podado_fixpt_w1[51] = 16'sb0010111010110111;
    modelo_podado_fixpt_w1[52] = 16'sb0010110101101010;
    modelo_podado_fixpt_w1[53] = 16'sb0010000111101100;
    modelo_podado_fixpt_w1[54] = 16'sb0000000000000000;
    modelo_podado_fixpt_w1[55] = 16'sb0000000000000000;
    modelo_podado_fixpt_w1[56] = 16'sb0010010101100100;
    modelo_podado_fixpt_w1[57] = 16'sb0000000000000000;
    modelo_podado_fixpt_w1[58] = 16'sb0100110010000101;
    modelo_podado_fixpt_w1[59] = 16'sb0000000000000000;
    modelo_podado_fixpt_w1[60] = 16'sb0000000000000000;
    modelo_podado_fixpt_w1[61] = 16'sb0000000000000000;
    modelo_podado_fixpt_w1[62] = 16'sb0000000000000000;
    modelo_podado_fixpt_w1[63] = 16'sb0000000000000000;
    modelo_podado_fixpt_w1[64] = 16'sb0000000000000000;
    modelo_podado_fixpt_w1[65] = 16'sb0000000000000000;
    modelo_podado_fixpt_w1[66] = 16'sb1011111011110110;
    modelo_podado_fixpt_w1[67] = 16'sb0000000000000000;
    modelo_podado_fixpt_w1[68] = 16'sb0000000000000000;
    modelo_podado_fixpt_w1[69] = 16'sb0000000000000000;
    modelo_podado_fixpt_w1[70] = 16'sb0000000000000000;
    modelo_podado_fixpt_w1[71] = 16'sb0000000000000000;
    modelo_podado_fixpt_w1[72] = 16'sb0000000000000000;
    modelo_podado_fixpt_w1[73] = 16'sb1100001010011001;
    modelo_podado_fixpt_w1[74] = 16'sb0000000000000000;
    modelo_podado_fixpt_w1[75] = 16'sb1101111010101011;
    modelo_podado_fixpt_w1[76] = 16'sb1101111010000000;
    modelo_podado_fixpt_w1[77] = 16'sb0010000001000011;
    modelo_podado_fixpt_w1[78] = 16'sb0000000000000000;
    modelo_podado_fixpt_w1[79] = 16'sb0011001111010101;
    modelo_podado_fixpt_w1[80] = 16'sb0000000000000000;
    modelo_podado_fixpt_w1[81] = 16'sb0000000000000000;
    modelo_podado_fixpt_w1[82] = 16'sb1100111011000110;
    modelo_podado_fixpt_w1[83] = 16'sb0000000000000000;
    modelo_podado_fixpt_w1[84] = 16'sb0000000000000000;
    modelo_podado_fixpt_w1[85] = 16'sb0000000000000000;
    modelo_podado_fixpt_w1[86] = 16'sb1101110101101000;
    modelo_podado_fixpt_w1[87] = 16'sb0000000000000000;
    modelo_podado_fixpt_w1[88] = 16'sb0000000000000000;
    modelo_podado_fixpt_w1[89] = 16'sb0000000000000000;
    modelo_podado_fixpt_w1[90] = 16'sb0000000000000000;
    modelo_podado_fixpt_w1[91] = 16'sb0000000000000000;
    modelo_podado_fixpt_w1[92] = 16'sb0000000000000000;
    modelo_podado_fixpt_w1[93] = 16'sb0011100110101010;
    modelo_podado_fixpt_w1[94] = 16'sb0000000000000000;
    modelo_podado_fixpt_w1[95] = 16'sb0011010000011001;
    modelo_podado_fixpt_w1[96] = 16'sb0000000000000000;
    modelo_podado_fixpt_w1[97] = 16'sb0101001001010011;
    modelo_podado_fixpt_w1[98] = 16'sb0000000000000000;
    modelo_podado_fixpt_w1[99] = 16'sb1011100110110001;
    modelo_podado_fixpt_w1[100] = 16'sb0100011011111101;
    modelo_podado_fixpt_w1[101] = 16'sb0000000000000000;
    modelo_podado_fixpt_w1[102] = 16'sb0000000000000000;
    modelo_podado_fixpt_w1[103] = 16'sb0111000000100100;
    modelo_podado_fixpt_w1[104] = 16'sb0000000000000000;
    modelo_podado_fixpt_w1[105] = 16'sb0000000000000000;
    modelo_podado_fixpt_w1[106] = 16'sb0000000000000000;
    modelo_podado_fixpt_w1[107] = 16'sb0000000000000000;
    modelo_podado_fixpt_w1[108] = 16'sb1101011001111110;
    modelo_podado_fixpt_w1[109] = 16'sb0000000000000000;
    modelo_podado_fixpt_w1[110] = 16'sb0000000000000000;
    modelo_podado_fixpt_w1[111] = 16'sb0010111100111111;
    modelo_podado_fixpt_w1[112] = 16'sb0011101010010100;
    modelo_podado_fixpt_w1[113] = 16'sb0110010111100010;
    modelo_podado_fixpt_w1[114] = 16'sb0000000000000000;
    modelo_podado_fixpt_w1[115] = 16'sb0011101001001101;
    modelo_podado_fixpt_w1[116] = 16'sb0101110100010010;
    modelo_podado_fixpt_w1[117] = 16'sb0000000000000000;
    modelo_podado_fixpt_w1[118] = 16'sb0011011100100101;
    modelo_podado_fixpt_w1[119] = 16'sb0000000000000000;
    modelo_podado_fixpt_w1[120] = 16'sb0000000000000000;
    modelo_podado_fixpt_w1[121] = 16'sb0000000000000000;
    modelo_podado_fixpt_w1[122] = 16'sb0000000000000000;
    modelo_podado_fixpt_w1[123] = 16'sb0000000000000000;
    modelo_podado_fixpt_w1[124] = 16'sb0000000000000000;
    modelo_podado_fixpt_w1[125] = 16'sb0000000000000000;
    modelo_podado_fixpt_w1[126] = 16'sb0000000000000000;
    modelo_podado_fixpt_w1[127] = 16'sb0000000000000000;
    modelo_podado_fixpt_w1[128] = 16'sb0000000000000000;
    modelo_podado_fixpt_w1[129] = 16'sb0000000000000000;
    modelo_podado_fixpt_w1[130] = 16'sb1100110010010001;
    modelo_podado_fixpt_w1[131] = 16'sb0011001110100111;
    modelo_podado_fixpt_w1[132] = 16'sb1011000000110110;
    modelo_podado_fixpt_w1[133] = 16'sb1100011111111010;
    modelo_podado_fixpt_w1[134] = 16'sb0010000110111101;
    modelo_podado_fixpt_w1[135] = 16'sb0000000000000000;
    modelo_podado_fixpt_w1[136] = 16'sb0000000000000000;
    modelo_podado_fixpt_w1[137] = 16'sb0000000000000000;
    modelo_podado_fixpt_w1[138] = 16'sb0011111110111100;
    modelo_podado_fixpt_w1[139] = 16'sb0011011000101010;
    modelo_podado_fixpt_w1[140] = 16'sb1100110110100111;
    modelo_podado_fixpt_w1[141] = 16'sb0000000000000000;
    modelo_podado_fixpt_w1[142] = 16'sb0000000000000000;
    modelo_podado_fixpt_w1[143] = 16'sb0000000000000000;
    modelo_podado_fixpt_w1[144] = 16'sb0000000000000000;
    modelo_podado_fixpt_w1[145] = 16'sb1100100111111010;
    modelo_podado_fixpt_w1[146] = 16'sb1101111011001000;
    modelo_podado_fixpt_w1[147] = 16'sb1011110001101110;
    modelo_podado_fixpt_w1[148] = 16'sb0000000000000000;
    modelo_podado_fixpt_w1[149] = 16'sb0000000000000000;
    modelo_podado_fixpt_w1[150] = 16'sb0000000000000000;
    modelo_podado_fixpt_w1[151] = 16'sb0000000000000000;
    modelo_podado_fixpt_w1[152] = 16'sb0001110001111010;
    modelo_podado_fixpt_w1[153] = 16'sb1100100101000101;
    modelo_podado_fixpt_w1[154] = 16'sb0000000000000000;
    modelo_podado_fixpt_w1[155] = 16'sb0000000000000000;
    modelo_podado_fixpt_w1[156] = 16'sb1011000010011000;
    modelo_podado_fixpt_w1[157] = 16'sb1001111111101110;
    modelo_podado_fixpt_w1[158] = 16'sb0000000000000000;
    modelo_podado_fixpt_w1[159] = 16'sb0100011001011111;
    modelo_podado_fixpt_w1[160] = 16'sb1100100001110011;
    modelo_podado_fixpt_w1[161] = 16'sb0000000000000000;
    modelo_podado_fixpt_w1[162] = 16'sb0000000000000000;
    modelo_podado_fixpt_w1[163] = 16'sb0000000000000000;
    modelo_podado_fixpt_w1[164] = 16'sb0000000000000000;
    modelo_podado_fixpt_w1[165] = 16'sb0011101101000111;
    modelo_podado_fixpt_w1[166] = 16'sb0000000000000000;
    modelo_podado_fixpt_w1[167] = 16'sb0000000000000000;
    modelo_podado_fixpt_w1[168] = 16'sb0000000000000000;
    modelo_podado_fixpt_w1[169] = 16'sb0000000000000000;
    modelo_podado_fixpt_w1[170] = 16'sb0000000000000000;
    modelo_podado_fixpt_w1[171] = 16'sb0000000000000000;
    modelo_podado_fixpt_w1[172] = 16'sb0000000000000000;
    modelo_podado_fixpt_w1[173] = 16'sb0000000000000000;
    modelo_podado_fixpt_w1[174] = 16'sb0000000000000000;
    modelo_podado_fixpt_w1[175] = 16'sb1100000010110011;
    modelo_podado_fixpt_w1[176] = 16'sb0000000000000000;
    modelo_podado_fixpt_w1[177] = 16'sb1100010110111010;
    modelo_podado_fixpt_w1[178] = 16'sb0000000000000000;
    modelo_podado_fixpt_w1[179] = 16'sb0000000000000000;
    modelo_podado_fixpt_w1[180] = 16'sb0000000000000000;
    modelo_podado_fixpt_w1[181] = 16'sb0000000000000000;
    modelo_podado_fixpt_w1[182] = 16'sb0000000000000000;
    modelo_podado_fixpt_w1[183] = 16'sb1101100111011111;
    modelo_podado_fixpt_w1[184] = 16'sb0011000100101111;
    modelo_podado_fixpt_w1[185] = 16'sb0000000000000000;
    modelo_podado_fixpt_w1[186] = 16'sb1100000110111111;
    modelo_podado_fixpt_w1[187] = 16'sb1011000101001111;
    modelo_podado_fixpt_w1[188] = 16'sb0000000000000000;
    modelo_podado_fixpt_w1[189] = 16'sb0010000001111000;
    modelo_podado_fixpt_w1[190] = 16'sb1100111001011001;
    modelo_podado_fixpt_w1[191] = 16'sb0000000000000000;
    modelo_podado_fixpt_w1[192] = 16'sb1101010110001110;
    modelo_podado_fixpt_w1[193] = 16'sb1001001100101111;
    modelo_podado_fixpt_w1[194] = 16'sb0010111001011100;
    modelo_podado_fixpt_w1[195] = 16'sb0000000000000000;
    modelo_podado_fixpt_w1[196] = 16'sb0000000000000000;
    modelo_podado_fixpt_w1[197] = 16'sb0011011010011010;
    modelo_podado_fixpt_w1[198] = 16'sb0000000000000000;
    modelo_podado_fixpt_w1[199] = 16'sb0010110100110000;
    modelo_podado_fixpt_w1[200] = 16'sb1101110100110011;
    modelo_podado_fixpt_w1[201] = 16'sb1101000111110011;
    modelo_podado_fixpt_w1[202] = 16'sb0000000000000000;
    modelo_podado_fixpt_w1[203] = 16'sb0000000000000000;
    modelo_podado_fixpt_w1[204] = 16'sb1101100001000110;
    modelo_podado_fixpt_w1[205] = 16'sb0000000000000000;
    modelo_podado_fixpt_w1[206] = 16'sb0000000000000000;
    modelo_podado_fixpt_w1[207] = 16'sb0000000000000000;
    modelo_podado_fixpt_w1[208] = 16'sb1101100011000000;
    modelo_podado_fixpt_w1[209] = 16'sb0000000000000000;
    modelo_podado_fixpt_w1[210] = 16'sb0010101100100010;
    modelo_podado_fixpt_w1[211] = 16'sb0000000000000000;
    modelo_podado_fixpt_w1[212] = 16'sb1110000100001001;
    modelo_podado_fixpt_w1[213] = 16'sb1101101111001110;
    modelo_podado_fixpt_w1[214] = 16'sb0000000000000000;
    modelo_podado_fixpt_w1[215] = 16'sb0000000000000000;
    modelo_podado_fixpt_w1[216] = 16'sb0000000000000000;
    modelo_podado_fixpt_w1[217] = 16'sb1011101010001100;
    modelo_podado_fixpt_w1[218] = 16'sb0000000000000000;
    modelo_podado_fixpt_w1[219] = 16'sb0011101110011011;
    modelo_podado_fixpt_w1[220] = 16'sb1100110101110001;
    modelo_podado_fixpt_w1[221] = 16'sb0010010010111100;
    modelo_podado_fixpt_w1[222] = 16'sb0000000000000000;
    modelo_podado_fixpt_w1[223] = 16'sb1100110110010110;
    modelo_podado_fixpt_w1[224] = 16'sb0000000000000000;
    modelo_podado_fixpt_w1[225] = 16'sb0000000000000000;
    modelo_podado_fixpt_w1[226] = 16'sb0000000000000000;
    modelo_podado_fixpt_w1[227] = 16'sb0000000000000000;
    modelo_podado_fixpt_w1[228] = 16'sb0011101011001010;
    modelo_podado_fixpt_w1[229] = 16'sb0010001010110000;
    modelo_podado_fixpt_w1[230] = 16'sb0000000000000000;
    modelo_podado_fixpt_w1[231] = 16'sb0000000000000000;
    modelo_podado_fixpt_w1[232] = 16'sb1101010001111111;
    modelo_podado_fixpt_w1[233] = 16'sb1101011100100001;
    modelo_podado_fixpt_w1[234] = 16'sb0000000000000000;
    modelo_podado_fixpt_w1[235] = 16'sb0000000000000000;
    modelo_podado_fixpt_w1[236] = 16'sb0000000000000000;
    modelo_podado_fixpt_w1[237] = 16'sb1100000010001011;
    modelo_podado_fixpt_w1[238] = 16'sb0000000000000000;
    modelo_podado_fixpt_w1[239] = 16'sb0000000000000000;
    modelo_podado_fixpt_w1[240] = 16'sb0011010100000111;
    modelo_podado_fixpt_w1[241] = 16'sb1101000110000010;
    modelo_podado_fixpt_w1[242] = 16'sb0000000000000000;
    modelo_podado_fixpt_w1[243] = 16'sb0000000000000000;
    modelo_podado_fixpt_w1[244] = 16'sb0000000000000000;
    modelo_podado_fixpt_w1[245] = 16'sb0000000000000000;
    modelo_podado_fixpt_w1[246] = 16'sb1100001010100010;
    modelo_podado_fixpt_w1[247] = 16'sb1010011010100000;
    modelo_podado_fixpt_w1[248] = 16'sb0000000000000000;
    modelo_podado_fixpt_w1[249] = 16'sb0100001110111111;
    modelo_podado_fixpt_w1[250] = 16'sb1011010101001101;
    modelo_podado_fixpt_w1[251] = 16'sb0000000000000000;
    modelo_podado_fixpt_w1[252] = 16'sb1011110111110010;
    modelo_podado_fixpt_w1[253] = 16'sb1100001101101001;
    modelo_podado_fixpt_w1[254] = 16'sb0000000000000000;
    modelo_podado_fixpt_w1[255] = 16'sb0000000000000000;
    modelo_podado_fixpt_w1[256] = 16'sb0010001000001000;
    modelo_podado_fixpt_w1[257] = 16'sb0000000000000000;
    modelo_podado_fixpt_w1[258] = 16'sb0010111001011111;
    modelo_podado_fixpt_w1[259] = 16'sb0100011010000000;
    modelo_podado_fixpt_w1[260] = 16'sb0000000000000000;
    modelo_podado_fixpt_w1[261] = 16'sb1011101110000101;
    modelo_podado_fixpt_w1[262] = 16'sb1101011111010101;
    modelo_podado_fixpt_w1[263] = 16'sb0000000000000000;
    modelo_podado_fixpt_w1[264] = 16'sb0000000000000000;
    modelo_podado_fixpt_w1[265] = 16'sb0000000000000000;
    modelo_podado_fixpt_w1[266] = 16'sb0000000000000000;
    modelo_podado_fixpt_w1[267] = 16'sb0000000000000000;
    modelo_podado_fixpt_w1[268] = 16'sb1101011100010101;
    modelo_podado_fixpt_w1[269] = 16'sb0000000000000000;
    modelo_podado_fixpt_w1[270] = 16'sb0000000000000000;
    modelo_podado_fixpt_w1[271] = 16'sb0010000001101010;
    modelo_podado_fixpt_w1[272] = 16'sb0000000000000000;
    modelo_podado_fixpt_w1[273] = 16'sb0000000000000000;
    modelo_podado_fixpt_w1[274] = 16'sb0000000000000000;
    modelo_podado_fixpt_w1[275] = 16'sb0000000000000000;
    modelo_podado_fixpt_w1[276] = 16'sb0000000000000000;
    modelo_podado_fixpt_w1[277] = 16'sb0100010100101111;
    modelo_podado_fixpt_w1[278] = 16'sb0000000000000000;
    modelo_podado_fixpt_w1[279] = 16'sb0000000000000000;
    modelo_podado_fixpt_w1[280] = 16'sb0110111111011001;
    modelo_podado_fixpt_w1[281] = 16'sb0000000000000000;
    modelo_podado_fixpt_w1[282] = 16'sb0101011101100001;
    modelo_podado_fixpt_w1[283] = 16'sb0111001010010101;
    modelo_podado_fixpt_w1[284] = 16'sb0000000000000000;
    modelo_podado_fixpt_w1[285] = 16'sb1101010111001101;
    modelo_podado_fixpt_w1[286] = 16'sb1100111000001101;
    modelo_podado_fixpt_w1[287] = 16'sb0000000000000000;
    modelo_podado_fixpt_w1[288] = 16'sb0000000000000000;
    modelo_podado_fixpt_w1[289] = 16'sb0000000000000000;
    modelo_podado_fixpt_w1[290] = 16'sb0011011111010101;
    modelo_podado_fixpt_w1[291] = 16'sb0000000000000000;
    modelo_podado_fixpt_w1[292] = 16'sb0100010000000001;
    modelo_podado_fixpt_w1[293] = 16'sb0100000011011010;
    modelo_podado_fixpt_w1[294] = 16'sb0000000000000000;
    modelo_podado_fixpt_w1[295] = 16'sb0100010110001110;
    modelo_podado_fixpt_w1[296] = 16'sb0010101110001111;
    modelo_podado_fixpt_w1[297] = 16'sb0000000000000000;
    modelo_podado_fixpt_w1[298] = 16'sb0011000001101101;
    modelo_podado_fixpt_w1[299] = 16'sb0010001000101011;
    modelo_podado_fixpt_w1[300] = 16'sb0000000000000000;
    modelo_podado_fixpt_w1[301] = 16'sb0000000000000000;
    modelo_podado_fixpt_w1[302] = 16'sb0000000000000000;
    modelo_podado_fixpt_w1[303] = 16'sb0000000000000000;
    modelo_podado_fixpt_w1[304] = 16'sb0000000000000000;
    modelo_podado_fixpt_w1[305] = 16'sb0000000000000000;
    modelo_podado_fixpt_w1[306] = 16'sb0000000000000000;
    modelo_podado_fixpt_w1[307] = 16'sb0000000000000000;
    modelo_podado_fixpt_w1[308] = 16'sb1110000001101111;
    modelo_podado_fixpt_w1[309] = 16'sb0000000000000000;
    modelo_podado_fixpt_w1[310] = 16'sb1101111000010100;
    modelo_podado_fixpt_w1[311] = 16'sb0000000000000000;
    modelo_podado_fixpt_w1[312] = 16'sb0000000000000000;
    modelo_podado_fixpt_w1[313] = 16'sb0000000000000000;
    modelo_podado_fixpt_w1[314] = 16'sb0000000000000000;
    modelo_podado_fixpt_w1[315] = 16'sb0000000000000000;
    modelo_podado_fixpt_w1[316] = 16'sb0000000000000000;
    modelo_podado_fixpt_w1[317] = 16'sb0000000000000000;
    modelo_podado_fixpt_w1[318] = 16'sb0000000000000000;
    modelo_podado_fixpt_w1[319] = 16'sb0000000000000000;
    modelo_podado_fixpt_w1[320] = 16'sb0000000000000000;
    modelo_podado_fixpt_w1[321] = 16'sb0000000000000000;
    modelo_podado_fixpt_w1[322] = 16'sb0010001101000011;
    modelo_podado_fixpt_w1[323] = 16'sb0000000000000000;
    modelo_podado_fixpt_w1[324] = 16'sb0000000000000000;
    modelo_podado_fixpt_w1[325] = 16'sb0000000000000000;
    modelo_podado_fixpt_w1[326] = 16'sb0010000010110110;
    modelo_podado_fixpt_w1[327] = 16'sb0000000000000000;
    modelo_podado_fixpt_w1[328] = 16'sb0010100111111011;
    modelo_podado_fixpt_w1[329] = 16'sb0000000000000000;
    modelo_podado_fixpt_w1[330] = 16'sb0010001001010111;
    modelo_podado_fixpt_w1[331] = 16'sb0000000000000000;
    modelo_podado_fixpt_w1[332] = 16'sb0000000000000000;
    modelo_podado_fixpt_w1[333] = 16'sb0010110000001010;
    modelo_podado_fixpt_w1[334] = 16'sb0000000000000000;
    modelo_podado_fixpt_w1[335] = 16'sb0011011000000010;
    modelo_podado_fixpt_w1[336] = 16'sb0101110100010001;
    modelo_podado_fixpt_w1[337] = 16'sb0010100000110101;
    modelo_podado_fixpt_w1[338] = 16'sb0000000000000000;
    modelo_podado_fixpt_w1[339] = 16'sb1100000111110011;
    modelo_podado_fixpt_w1[340] = 16'sb0101101111100110;
    modelo_podado_fixpt_w1[341] = 16'sb0000000000000000;
    modelo_podado_fixpt_w1[342] = 16'sb0011111010000111;
    modelo_podado_fixpt_w1[343] = 16'sb0110010101110010;
    modelo_podado_fixpt_w1[344] = 16'sb0000000000000000;
    modelo_podado_fixpt_w1[345] = 16'sb1101010101101111;
    modelo_podado_fixpt_w1[346] = 16'sb0000000000000000;
    modelo_podado_fixpt_w1[347] = 16'sb1101101111000100;
    modelo_podado_fixpt_w1[348] = 16'sb1101111100111011;
    modelo_podado_fixpt_w1[349] = 16'sb1101111010011000;
    modelo_podado_fixpt_w1[350] = 16'sb0011111011110110;
    modelo_podado_fixpt_w1[351] = 16'sb0011100001110111;
    modelo_podado_fixpt_w1[352] = 16'sb0000000000000000;
    modelo_podado_fixpt_w1[353] = 16'sb0011101110000110;
    modelo_podado_fixpt_w1[354] = 16'sb0000000000000000;
    modelo_podado_fixpt_w1[355] = 16'sb0000000000000000;
    modelo_podado_fixpt_w1[356] = 16'sb0100011100010010;
    modelo_podado_fixpt_w1[357] = 16'sb0100011100010001;
    modelo_podado_fixpt_w1[358] = 16'sb0000000000000000;
    modelo_podado_fixpt_w1[359] = 16'sb0000000000000000;
    modelo_podado_fixpt_w1[360] = 16'sb0000000000000000;
    modelo_podado_fixpt_w1[361] = 16'sb0011100110000111;
    modelo_podado_fixpt_w1[362] = 16'sb1110000110111000;
    modelo_podado_fixpt_w1[363] = 16'sb0101001110101010;
    modelo_podado_fixpt_w1[364] = 16'sb0000000000000000;
    modelo_podado_fixpt_w1[365] = 16'sb0000000000000000;
    modelo_podado_fixpt_w1[366] = 16'sb0011111101011111;
    modelo_podado_fixpt_w1[367] = 16'sb0011100100110000;
    modelo_podado_fixpt_w1[368] = 16'sb0000000000000000;
    modelo_podado_fixpt_w1[369] = 16'sb1011011111011000;
    modelo_podado_fixpt_w1[370] = 16'sb0111110101101101;
    modelo_podado_fixpt_w1[371] = 16'sb0000000000000000;
    modelo_podado_fixpt_w1[372] = 16'sb0100001000110011;
    modelo_podado_fixpt_w1[373] = 16'sb0101111011111101;
    modelo_podado_fixpt_w1[374] = 16'sb1101010100000000;
    modelo_podado_fixpt_w1[375] = 16'sb1100010001100010;
    modelo_podado_fixpt_w1[376] = 16'sb0000000000000000;
    modelo_podado_fixpt_w1[377] = 16'sb0011001011111011;
    modelo_podado_fixpt_w1[378] = 16'sb0000000000000000;
    modelo_podado_fixpt_w1[379] = 16'sb1101000000101000;
    modelo_podado_fixpt_w1[380] = 16'sb0010100001111100;
    modelo_podado_fixpt_w1[381] = 16'sb0011000001111100;
    modelo_podado_fixpt_w1[382] = 16'sb0000000000000000;
    modelo_podado_fixpt_w1[383] = 16'sb0101001110001010;
    modelo_podado_fixpt_w1[384] = 16'sb0000000000000000;
    modelo_podado_fixpt_w1[385] = 16'sb0000000000000000;
    modelo_podado_fixpt_w1[386] = 16'sb0101110101000010;
    modelo_podado_fixpt_w1[387] = 16'sb0000000000000000;
    modelo_podado_fixpt_w1[388] = 16'sb0011101111100101;
    modelo_podado_fixpt_w1[389] = 16'sb0010111110101110;
    modelo_podado_fixpt_w1[390] = 16'sb0000000000000000;
    modelo_podado_fixpt_w1[391] = 16'sb0000000000000000;
    modelo_podado_fixpt_w1[392] = 16'sb0000000000000000;
    modelo_podado_fixpt_w1[393] = 16'sb0000000000000000;
    modelo_podado_fixpt_w1[394] = 16'sb0000000000000000;
    modelo_podado_fixpt_w1[395] = 16'sb0001111001001010;
    modelo_podado_fixpt_w1[396] = 16'sb0010100001011111;
    modelo_podado_fixpt_w1[397] = 16'sb0000000000000000;
    modelo_podado_fixpt_w1[398] = 16'sb1101001101101010;
    modelo_podado_fixpt_w1[399] = 16'sb0000000000000000;
    modelo_podado_fixpt_w1[400] = 16'sb1100100101101101;
    modelo_podado_fixpt_w1[401] = 16'sb1101100001011000;
    modelo_podado_fixpt_w1[402] = 16'sb0000000000000000;
    modelo_podado_fixpt_w1[403] = 16'sb1100011001011010;
    modelo_podado_fixpt_w1[404] = 16'sb1101011010110101;
    modelo_podado_fixpt_w1[405] = 16'sb0011001100100010;
    modelo_podado_fixpt_w1[406] = 16'sb0000000000000000;
    modelo_podado_fixpt_w1[407] = 16'sb0010000111001111;
    modelo_podado_fixpt_w1[408] = 16'sb1101101110100011;
    modelo_podado_fixpt_w1[409] = 16'sb0010111000001000;
    modelo_podado_fixpt_w1[410] = 16'sb0000000000000000;
    modelo_podado_fixpt_w1[411] = 16'sb0000000000000000;
    modelo_podado_fixpt_w1[412] = 16'sb0010011010101111;
    modelo_podado_fixpt_w1[413] = 16'sb0000000000000000;
    modelo_podado_fixpt_w1[414] = 16'sb1100111110011110;
    modelo_podado_fixpt_w1[415] = 16'sb0000000000000000;
    modelo_podado_fixpt_w1[416] = 16'sb0000000000000000;
    modelo_podado_fixpt_w1[417] = 16'sb0000000000000000;
    modelo_podado_fixpt_w1[418] = 16'sb0000000000000000;
    modelo_podado_fixpt_w1[419] = 16'sb0011000111011101;
    modelo_podado_fixpt_w1[420] = 16'sb0000000000000000;
    modelo_podado_fixpt_w1[421] = 16'sb0000000000000000;
    modelo_podado_fixpt_w1[422] = 16'sb0000000000000000;
    modelo_podado_fixpt_w1[423] = 16'sb0000000000000000;
    modelo_podado_fixpt_w1[424] = 16'sb0000000000000000;
    modelo_podado_fixpt_w1[425] = 16'sb1100011110110101;
    modelo_podado_fixpt_w1[426] = 16'sb1101010110011111;
    modelo_podado_fixpt_w1[427] = 16'sb0000000000000000;
    modelo_podado_fixpt_w1[428] = 16'sb0011100001010011;
    modelo_podado_fixpt_w1[429] = 16'sb0010110101000101;
    modelo_podado_fixpt_w1[430] = 16'sb1011001110010011;
    modelo_podado_fixpt_w1[431] = 16'sb0000000000000000;
    modelo_podado_fixpt_w1[432] = 16'sb1011111011010110;
    modelo_podado_fixpt_w1[433] = 16'sb1011000001011000;
    modelo_podado_fixpt_w1[434] = 16'sb0000000000000000;
    modelo_podado_fixpt_w1[435] = 16'sb0010111110111101;
    modelo_podado_fixpt_w1[436] = 16'sb0000000000000000;
    modelo_podado_fixpt_w1[437] = 16'sb0000000000000000;
    modelo_podado_fixpt_w1[438] = 16'sb0000000000000000;
    modelo_podado_fixpt_w1[439] = 16'sb0000000000000000;
    modelo_podado_fixpt_w1[440] = 16'sb0000000000000000;
    modelo_podado_fixpt_w1[441] = 16'sb1101100011101111;
    modelo_podado_fixpt_w1[442] = 16'sb0000000000000000;
    modelo_podado_fixpt_w1[443] = 16'sb1011111101101111;
    modelo_podado_fixpt_w1[444] = 16'sb0000000000000000;
    modelo_podado_fixpt_w1[445] = 16'sb0000000000000000;
    modelo_podado_fixpt_w1[446] = 16'sb0000000000000000;
    modelo_podado_fixpt_w1[447] = 16'sb1101100101010110;
    modelo_podado_fixpt_w1[448] = 16'sb0000000000000000;
    modelo_podado_fixpt_w1[449] = 16'sb0000000000000000;
    modelo_podado_fixpt_w1[450] = 16'sb0000000000000000;
    modelo_podado_fixpt_w1[451] = 16'sb0000000000000000;
    modelo_podado_fixpt_w1[452] = 16'sb0000000000000000;
    modelo_podado_fixpt_w1[453] = 16'sb1101010110010001;
    modelo_podado_fixpt_w1[454] = 16'sb1100111101101111;
    modelo_podado_fixpt_w1[455] = 16'sb0000000000000000;
    modelo_podado_fixpt_w1[456] = 16'sb0000000000000000;
    modelo_podado_fixpt_w1[457] = 16'sb0000000000000000;
    modelo_podado_fixpt_w1[458] = 16'sb0000000000000000;
    modelo_podado_fixpt_w1[459] = 16'sb0000000000000000;
    modelo_podado_fixpt_w1[460] = 16'sb0000000000000000;
    modelo_podado_fixpt_w1[461] = 16'sb0000000000000000;
    modelo_podado_fixpt_w1[462] = 16'sb0000000000000000;
    modelo_podado_fixpt_w1[463] = 16'sb0000000000000000;
    modelo_podado_fixpt_w1[464] = 16'sb0000000000000000;
    modelo_podado_fixpt_w1[465] = 16'sb0010010110101110;
    modelo_podado_fixpt_w1[466] = 16'sb0000000000000000;
    modelo_podado_fixpt_w1[467] = 16'sb0000000000000000;
    modelo_podado_fixpt_w1[468] = 16'sb0000000000000000;
    modelo_podado_fixpt_w1[469] = 16'sb0000000000000000;
    modelo_podado_fixpt_w1[470] = 16'sb0000000000000000;
    modelo_podado_fixpt_w1[471] = 16'sb0000000000000000;
    modelo_podado_fixpt_w1[472] = 16'sb1101011100110011;
    modelo_podado_fixpt_w1[473] = 16'sb0000000000000000;
    modelo_podado_fixpt_w1[474] = 16'sb0000000000000000;
    modelo_podado_fixpt_w1[475] = 16'sb0000000000000000;
    modelo_podado_fixpt_w1[476] = 16'sb0000000000000000;
    modelo_podado_fixpt_w1[477] = 16'sb1101010000001101;
    modelo_podado_fixpt_w1[478] = 16'sb0000000000000000;
    modelo_podado_fixpt_w1[479] = 16'sb0000000000000000;
    modelo_podado_fixpt_tmp_1 = 16'b0000000000000000;
    modelo_podado_fixpt_acum_2 = 16'sb0000000000000000;
    modelo_podado_fixpt_div_temp = 44'sh00000000000;
    modelo_podado_fixpt_cast_0 = 17'sb00000000000000000;
    modelo_podado_fixpt_slice_cast_0 = 44'sh00000000000;
    modelo_podado_fixpt_acum_1 = 16'sb0000000000000000;
    modelo_podado_fixpt_cast = 17'sb00000000000000000;
    modelo_podado_fixpt_slice_cast = 44'sh00000000000;
    modelo_podado_fixpt_cast_4 = 44'sh00000000000;
    //HDL code generation from MATLAB function: modelo_podado_fixpt
    //%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    //                                                                          %
    //          Generated by MATLAB 9.13 and Fixed-Point Designer 7.5           %
    //                                                                          %
    //%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    // Definición de Pesos y Biases
    // Capa oculta
    // Capa de salida
    modelo_podado_fixpt_acum = 16'sb0000000000000000;

    for(modelo_podado_fixpt_i = 32'sd0; modelo_podado_fixpt_i <= 32'sd15; modelo_podado_fixpt_i = modelo_podado_fixpt_i + 32'sd1) begin
      modelo_podado_fixpt_acum_2 = 16'sb0000000000000000;

      for(modelo_podado_fixpt_i_0 = 32'sd0; modelo_podado_fixpt_i_0 <= 32'sd29; modelo_podado_fixpt_i_0 = modelo_podado_fixpt_i_0 + 32'sd1) begin
        modelo_podado_fixpt_add_cast_2[modelo_podado_fixpt_i_0] = {modelo_podado_fixpt_acum_2[15], {modelo_podado_fixpt_acum_2, 17'b00000000000000000}};
        modelo_podado_fixpt_cast_1[modelo_podado_fixpt_i_0] = {1'b0, in[modelo_podado_fixpt_i_0]};
        modelo_podado_fixpt_mul_temp[modelo_podado_fixpt_i_0] = modelo_podado_fixpt_cast_1[modelo_podado_fixpt_i_0] * modelo_podado_fixpt_w1[modelo_podado_fixpt_i_0 + (32'sd30 * modelo_podado_fixpt_i)];
        modelo_podado_fixpt_add_cast_3[modelo_podado_fixpt_i_0] = modelo_podado_fixpt_mul_temp[modelo_podado_fixpt_i_0][31:0];
        modelo_podado_fixpt_add_cast_4[modelo_podado_fixpt_i_0] = {{2{modelo_podado_fixpt_add_cast_3[modelo_podado_fixpt_i_0][31]}}, modelo_podado_fixpt_add_cast_3[modelo_podado_fixpt_i_0]};
        modelo_podado_fixpt_add_temp_0[modelo_podado_fixpt_i_0] = modelo_podado_fixpt_add_cast_2[modelo_podado_fixpt_i_0] + modelo_podado_fixpt_add_cast_4[modelo_podado_fixpt_i_0];
        modelo_podado_fixpt_acum_2 = modelo_podado_fixpt_add_temp_0[modelo_podado_fixpt_i_0][32:17];
      end

      modelo_podado_fixpt_add_cast_0[modelo_podado_fixpt_i] = {modelo_podado_fixpt_acum_2[15], {modelo_podado_fixpt_acum_2, 2'b00}};
      modelo_podado_fixpt_add_cast_1[modelo_podado_fixpt_i] = {{3{modelo_podado_fixpt_b1_0[modelo_podado_fixpt_i][15]}}, modelo_podado_fixpt_b1_0[modelo_podado_fixpt_i]};
      modelo_podado_fixpt_add_temp[modelo_podado_fixpt_i] = modelo_podado_fixpt_add_cast_0[modelo_podado_fixpt_i] + modelo_podado_fixpt_add_cast_1[modelo_podado_fixpt_i];
      modelo_podado_fixpt_acum_1 = modelo_podado_fixpt_add_temp[modelo_podado_fixpt_i][17:2];
      if (modelo_podado_fixpt_acum_1 < 16'sb0000000000000000) begin
        modelo_podado_fixpt_tmp_1 = 16'b0000000000000000;
      end
      else begin
        modelo_podado_fixpt_tmp_1 = {modelo_podado_fixpt_acum_1[14:0], 1'b0};
      end
      modelo_podado_fixpt_add_cast_5[modelo_podado_fixpt_i] = {modelo_podado_fixpt_acum[15], {modelo_podado_fixpt_acum, 16'b0000000000000000}};
      modelo_podado_fixpt_cast_3[modelo_podado_fixpt_i] = {1'b0, modelo_podado_fixpt_tmp_1};
      modelo_podado_fixpt_mul_temp_0[modelo_podado_fixpt_i] = modelo_podado_fixpt_cast_3[modelo_podado_fixpt_i] * modelo_podado_fixpt_w[modelo_podado_fixpt_i];
      modelo_podado_fixpt_add_cast_6[modelo_podado_fixpt_i] = modelo_podado_fixpt_mul_temp_0[modelo_podado_fixpt_i][31:0];
      modelo_podado_fixpt_add_cast_7[modelo_podado_fixpt_i] = {modelo_podado_fixpt_add_cast_6[modelo_podado_fixpt_i][31], modelo_podado_fixpt_add_cast_6[modelo_podado_fixpt_i]};
      modelo_podado_fixpt_add_temp_1[modelo_podado_fixpt_i] = modelo_podado_fixpt_add_cast_5[modelo_podado_fixpt_i] + modelo_podado_fixpt_add_cast_7[modelo_podado_fixpt_i];
      modelo_podado_fixpt_acum = modelo_podado_fixpt_add_temp_1[modelo_podado_fixpt_i][31:16];
    end

    modelo_podado_fixpt_t_0 = 21'sb111111001000011001000;
    modelo_podado_fixpt_add_cast = modelo_podado_fixpt_t_0[19:4];
    modelo_podado_fixpt_acum_0 = modelo_podado_fixpt_acum + modelo_podado_fixpt_add_cast;
    if (modelo_podado_fixpt_acum_0 < 16'sb0000000000000000) begin
      modelo_podado_fixpt_cast = {modelo_podado_fixpt_acum_0[15], modelo_podado_fixpt_acum_0};
      modelo_podado_fixpt_cast_0 =  - (modelo_podado_fixpt_cast);
      modelo_podado_fixpt_tmp = modelo_podado_fixpt_cast_0[15:0];
    end
    else begin
      modelo_podado_fixpt_tmp = modelo_podado_fixpt_acum_0;
    end
    modelo_podado_fixpt_cast_2 = {{2{modelo_podado_fixpt_acum_0[15]}}, {modelo_podado_fixpt_acum_0, 15'b000000000000000}};
    modelo_podado_fixpt_a1 = modelo_podado_fixpt_cast_2[31:0];
    if (modelo_podado_fixpt_a1 < 32'sb00000000000000000000000000000000) begin
      modelo_podado_fixpt_tmp_0 = 50'sh2000000000000;
    end
    else begin
      modelo_podado_fixpt_tmp_0 = 50'sh1FFFFFFFFFFFF;
    end
    modelo_podado_fixpt_add_cast_8 = {{2{modelo_podado_fixpt_tmp[15]}}, modelo_podado_fixpt_tmp};
    modelo_podado_fixpt_b1 = modelo_podado_fixpt_add_cast_8 + 18'sb000001000000000000;
    if ( ! (modelo_podado_fixpt_b1 == 18'sb000000000000000000)) begin
      modelo_podado_fixpt_slice_cast = {modelo_podado_fixpt_a1, 12'b000000000000};
      if (modelo_podado_fixpt_slice_cast[43] == modelo_podado_fixpt_b1[17]) begin
        modelo_podado_fixpt_slice_cast_0 = 44'sh7FFFFFFFFFF;
      end
      else begin
        modelo_podado_fixpt_slice_cast_0 = 44'sh80000000000;
      end
      modelo_podado_fixpt_cast_4 = {modelo_podado_fixpt_a1, 12'b000000000000};
      if (modelo_podado_fixpt_b1 == 31'sd0) begin
        modelo_podado_fixpt_div_temp = modelo_podado_fixpt_slice_cast_0;
      end
      else begin
        modelo_podado_fixpt_div_temp = modelo_podado_fixpt_cast_4 / modelo_podado_fixpt_b1;
      end
      modelo_podado_fixpt_tmp_0 = {{6{modelo_podado_fixpt_div_temp[43]}}, modelo_podado_fixpt_div_temp};
    end
    //     y = sigmoide(acum);
    // y = 0.4*tanh(acum) + 0.5;
    modelo_podado_fixpt_add_cast_9 = {{2{modelo_podado_fixpt_tmp_0[49]}}, modelo_podado_fixpt_tmp_0};
    modelo_podado_fixpt_add_temp_2 = modelo_podado_fixpt_add_cast_9 + 52'sh0000008000000;
    modelo_podado_fixpt_cast_5 = modelo_podado_fixpt_add_temp_2[27:12];
    if (modelo_podado_fixpt_cast_5 >= 16'b1000000000000000) begin
      out_1 = 1'b1;
    end
    else begin
      out_1 = 1'b0;
    end
  end



  assign out = out_1;

endmodule  // modelo_podado_fixpt

